use hulk_ir::{
    DataId, FunctionId, IrBinaryOp, IrData, IrDataValue, IrFunction, IrInstr, IrPlace, IrProgram,
    IrType, IrTypeRef, IrUnaryOp, IrValue, LabelId, LocalId, ParamId, TempId,
};
use std::collections::HashMap;
use std::fmt;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LlvmCodegenError {
    UnsupportedType {
        ty: IrTypeRef,
    },
    UnsupportedInstruction {
        instruction: &'static str,
    },
    UnsupportedOperation {
        message: String,
    },
    UnknownFunction {
        name: String,
    },
    UnknownValue {
        name: String,
    },
    MissingData {
        id: DataId,
    },
    TypeMismatch {
        expected: IrTypeRef,
        found: IrTypeRef,
    },
    MissingEntry {
        id: FunctionId,
    },
}

impl fmt::Display for LlvmCodegenError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            LlvmCodegenError::UnsupportedType { ty } => {
                write!(f, "unsupported type for LLVM codegen: {ty}")
            }
            LlvmCodegenError::UnsupportedInstruction { instruction } => {
                write!(
                    f,
                    "unsupported IR instruction for LLVM codegen: {instruction}"
                )
            }
            LlvmCodegenError::UnsupportedOperation { message } => write!(f, "{message}"),
            LlvmCodegenError::UnknownFunction { name } => write!(f, "unknown function '{name}'"),
            LlvmCodegenError::UnknownValue { name } => write!(f, "unknown value '{name}'"),
            LlvmCodegenError::MissingData { id } => {
                write!(f, "IR static data #{} was not found", id.0)
            }
            LlvmCodegenError::TypeMismatch { expected, found } => {
                write!(f, "type mismatch: expected {expected}, found {found}")
            }
            LlvmCodegenError::MissingEntry { id } => {
                write!(f, "IR entry function #{} was not found", id.0)
            }
        }
    }
}

impl std::error::Error for LlvmCodegenError {}

pub fn emit_llvm(program: &IrProgram) -> Result<String, LlvmCodegenError> {
    LlvmEmitter::new(program).emit_program()
}

#[derive(Debug, Clone)]
struct FunctionSig {
    llvm_name: String,
    params: Vec<IrTypeRef>,
    ret: IrTypeRef,
}

struct LlvmEmitter<'a> {
    program: &'a IrProgram,
    signatures: HashMap<String, FunctionSig>,
    data: HashMap<DataId, &'a IrData>,
    types: HashMap<String, &'a IrType>,
}

impl<'a> LlvmEmitter<'a> {
    fn new(program: &'a IrProgram) -> Self {
        let mut signatures = HashMap::new();
        for function in &program.functions {
            signatures.insert(
                function.name.clone(),
                FunctionSig {
                    llvm_name: llvm_function_name(function),
                    params: function
                        .params
                        .iter()
                        .map(|param| param.ty.clone())
                        .collect(),
                    ret: function.return_type.clone(),
                },
            );
        }
        let data = program
            .data
            .iter()
            .map(|item| (item.id, item))
            .collect::<HashMap<_, _>>();
        let types = program
            .types
            .iter()
            .map(|item| (item.name.clone(), item))
            .collect::<HashMap<_, _>>();
        Self {
            program,
            signatures,
            data,
            types,
        }
    }

    fn emit_program(&self) -> Result<String, LlvmCodegenError> {
        if !self
            .program
            .functions
            .iter()
            .any(|function| function.id == self.program.entry)
        {
            return Err(LlvmCodegenError::MissingEntry {
                id: self.program.entry,
            });
        }

        let mut out = String::new();
        out.push_str("; generated by hulk-codegen-llvm\n");
        out.push_str("declare void @hulk_print_number(double)\n");
        out.push_str("declare void @hulk_print_bool(i8)\n");
        out.push_str("declare double @hulk_sqrt(double)\n");
        out.push_str("declare double @hulk_sin(double)\n");
        out.push_str("declare double @hulk_cos(double)\n");
        out.push_str("declare double @hulk_exp(double)\n");
        out.push_str("declare double @hulk_log(double, double)\n");
        out.push_str("declare double @hulk_pow(double, double)\n");
        out.push_str("declare double @hulk_rand()\n");
        out.push_str("declare void @hulk_print_string(ptr)\n");
        out.push_str("declare ptr @hulk_string_concat(ptr, ptr)\n");
        out.push_str("declare i8 @hulk_string_equals(ptr, ptr)\n");
        out.push_str("declare ptr @hulk_string_from_number(double)\n");
        out.push_str("declare ptr @hulk_string_from_bool(i8)\n");
        out.push_str("declare void @hulk_runtime_error(ptr)\n");
        out.push_str("declare ptr @hulk_alloc_object(i64, i64, ptr)\n");
        out.push_str("declare ptr @hulk_object_method(ptr, i64)\n");
        out.push_str("declare i8 @hulk_object_is(ptr, i64)\n");
        out.push_str("declare ptr @hulk_object_as(ptr, i64)\n");
        out.push_str("declare void @hulk_object_set_number(ptr, i64, double)\n");
        out.push_str("declare void @hulk_object_set_bool(ptr, i64, i8)\n");
        out.push_str("declare void @hulk_object_set_string(ptr, i64, ptr)\n");
        out.push_str("declare void @hulk_object_set_object(ptr, i64, ptr)\n");
        out.push_str("declare double @hulk_object_get_number(ptr, i64)\n");
        out.push_str("declare i8 @hulk_object_get_bool(ptr, i64)\n");
        out.push_str("declare ptr @hulk_object_get_string(ptr, i64)\n");
        out.push_str("declare ptr @hulk_object_get_object(ptr, i64)\n");
        out.push_str("declare ptr @hulk_range(double, double)\n");
        out.push_str("declare ptr @hulk_vector_new()\n");
        out.push_str("declare void @hulk_vector_push(ptr, i64)\n");
        out.push_str("declare i64 @hulk_vector_get(ptr, i64)\n");
        out.push_str("declare void @hulk_vector_set(ptr, i64, i64)\n");
        out.push_str("declare i64 @hulk_vector_len(ptr)\n");
        out.push_str("declare ptr @hulk_closure_alloc(ptr, i64)\n");
        out.push_str("declare void @hulk_closure_set_capture(ptr, i64, ptr)\n");
        out.push_str("declare ptr @hulk_closure_get_capture(ptr, i64)\n");
        out.push('\n');
        self.emit_data(&mut out)?;

        for function in &self.program.functions {
            FunctionEmitter::new(function, &self.signatures, &self.data, &self.types)
                .emit(&mut out)?;
            out.push('\n');
        }

        self.emit_main(&mut out)?;
        Ok(out)
    }

    fn emit_data(&self, out: &mut String) -> Result<(), LlvmCodegenError> {
        out.push_str("%HulkString = type { i64, ptr }\n");
        out.push_str("%HulkVTable = type { i64, ptr, i64, ptr }\n\n");
        for data in &self.program.data {
            match &data.value {
                IrDataValue::String(value) => {
                    let base_name = format!("str_{}", data.id.0);
                    let byte_name = format!("@{}_data", base_name);
                    let desc_name = format!("@{}", base_name);
                    let bytes = llvm_string_bytes(value.as_bytes());
                    out.push_str(&format!(
                        "{byte_name} = private unnamed_addr constant [{} x i8] c\"{bytes}\"\n",
                        value.as_bytes().len() + 1
                    ));
                    out.push_str(&format!(
                        "{desc_name} = private unnamed_addr constant %HulkString {{ i64 {}, ptr {byte_name} }}\n",
                        value.as_bytes().len()
                    ));
                }
                IrDataValue::Number(_) | IrDataValue::Boolean(_) => {}
            }
        }
        self.emit_vtables(out)?;
        out.push('\n');
        Ok(())
    }

    fn emit_vtables(&self, out: &mut String) -> Result<(), LlvmCodegenError> {
        for ty in &self.program.types {
            let methods_name = vtable_methods_global_name(&ty.name);
            let vtable_name = vtable_global_name(&ty.name);
            let mut methods = ty.methods.iter().collect::<Vec<_>>();
            methods.sort_by_key(|method| method.slot.0);
            for (expected_slot, method) in methods.iter().enumerate() {
                let expected_slot = expected_slot as u32;
                if method.slot.0 != expected_slot {
                    return Err(LlvmCodegenError::UnsupportedOperation {
                        message: format!(
                            "type '{}' has non-contiguous method slots: expected slot {}, found slot {} on method '{}' (slots must be contiguous from 0 to {})",
                            ty.name,
                            expected_slot,
                            method.slot.0,
                            method.name,
                            ty.methods.len().saturating_sub(1)
                        ),
                    });
                }
            }
            let method_refs = methods
                .iter()
                .map(|method| {
                    let sig = self.signatures.get(&method.function).ok_or_else(|| {
                        LlvmCodegenError::UnknownFunction {
                            name: method.function.clone(),
                        }
                    })?;
                    Ok(format!("ptr @{}", sig.llvm_name))
                })
                .collect::<Result<Vec<_>, LlvmCodegenError>>()?;
            out.push_str(&format!(
                "{methods_name} = private constant [{} x ptr] [{}]\n",
                method_refs.len(),
                method_refs.join(", ")
            ));

            let parent = ty
                .parent
                .as_ref()
                .map(|parent| format!("ptr {}", vtable_global_name(parent)))
                .unwrap_or_else(|| "ptr null".to_string());
            out.push_str(&format!(
                "{vtable_name} = private constant %HulkVTable {{ i64 {}, {parent}, i64 {}, ptr {methods_name} }}\n",
                ty.id.0,
                method_refs.len()
            ));
        }
        Ok(())
    }

    fn emit_main(&self, out: &mut String) -> Result<(), LlvmCodegenError> {
        let entry = self
            .program
            .functions
            .iter()
            .find(|function| function.id == self.program.entry)
            .ok_or(LlvmCodegenError::MissingEntry {
                id: self.program.entry,
            })?;
        let entry_ret = llvm_type(&entry.return_type)?;
        out.push_str("define i32 @main() {\n");
        out.push_str("entry:\n");
        out.push_str(&format!(
            "  %entry_result = call {entry_ret} @{}()\n",
            llvm_function_name(entry)
        ));
        out.push_str("  ret i32 0\n");
        out.push_str("}\n");
        Ok(())
    }
}

struct FunctionEmitter<'a> {
    function: &'a IrFunction,
    signatures: &'a HashMap<String, FunctionSig>,
    data: &'a HashMap<DataId, &'a IrData>,
    types: &'a HashMap<String, &'a IrType>,
    local_types: HashMap<LocalId, IrTypeRef>,
    temp_types: HashMap<TempId, IrTypeRef>,
    param_types: HashMap<ParamId, IrTypeRef>,
    lines: Vec<String>,
    next_value_id: u32,
    block_terminated: bool,
}

impl<'a> FunctionEmitter<'a> {
    fn new(
        function: &'a IrFunction,
        signatures: &'a HashMap<String, FunctionSig>,
        data: &'a HashMap<DataId, &'a IrData>,
        types: &'a HashMap<String, &'a IrType>,
    ) -> Self {
        let local_types = function
            .locals
            .iter()
            .map(|local| (local.id, local.ty.clone()))
            .collect();
        let temp_types = function
            .temps
            .iter()
            .map(|temp| (temp.id, temp.ty.clone()))
            .collect();
        let param_types = function
            .params
            .iter()
            .map(|param| (param.id, param.ty.clone()))
            .collect();

        Self {
            function,
            signatures,
            data,
            types,
            local_types,
            temp_types,
            param_types,
            lines: Vec::new(),
            next_value_id: 0,
            block_terminated: false,
        }
    }

    fn emit(mut self, out: &mut String) -> Result<(), LlvmCodegenError> {
        let ret_ty = llvm_type(&self.function.return_type)?;
        let params = self
            .function
            .params
            .iter()
            .map(|param| Ok(format!("{} %p{}", llvm_type(&param.ty)?, param.id.0)))
            .collect::<Result<Vec<_>, LlvmCodegenError>>()?
            .join(", ");

        out.push_str(&format!(
            "define {ret_ty} @{}({params}) {{\n",
            llvm_function_name(self.function)
        ));
        out.push_str("entry:\n");

        for local in &self.function.locals {
            out.push_str(&format!(
                "  %l{}.addr = alloca {}\n",
                local.id.0,
                llvm_type(&local.ty)?
            ));
        }
        for temp in &self.function.temps {
            out.push_str(&format!(
                "  %t{}.addr = alloca {}\n",
                temp.id.0,
                llvm_type(&temp.ty)?
            ));
        }

        for instr in &self.function.body {
            self.emit_instr(instr)?;
        }

        if !self.block_terminated {
            self.lines.push("  unreachable".to_string());
        }

        for line in self.lines {
            out.push_str(&line);
            out.push('\n');
        }
        out.push_str("}\n");
        Ok(())
    }

    fn emit_instr(&mut self, instr: &IrInstr) -> Result<(), LlvmCodegenError> {
        match instr {
            IrInstr::Label(label) => {
                self.start_label(*label);
                Ok(())
            }
            IrInstr::Assign { dst, src } => {
                self.store_value(*dst, src)?;
                Ok(())
            }
            IrInstr::Unary { dst, op, value } => self.emit_unary(*dst, op, value),
            IrInstr::Binary {
                dst,
                op,
                left,
                right,
            } => self.emit_binary(*dst, op, left, right),
            IrInstr::Jump(label) => {
                self.lines.push(format!("  br label %L{}", label.0));
                self.block_terminated = true;
                Ok(())
            }
            IrInstr::Branch {
                cond,
                then_label,
                else_label,
            } => {
                let cond = self.read_value_as(cond, &IrTypeRef::Boolean)?;
                self.lines.push(format!(
                    "  br i1 {}, label %L{}, label %L{}",
                    cond.operand, then_label.0, else_label.0
                ));
                self.block_terminated = true;
                Ok(())
            }
            IrInstr::Call {
                dst,
                function,
                args,
            } => self.emit_call(*dst, function, args),
            IrInstr::Return(value) => self.emit_return(value.as_ref()),
            IrInstr::Allocate { dst, type_name } => self.emit_allocate(*dst, type_name),
            IrInstr::GetAttr { dst, object, attr } => self.emit_get_attr(*dst, object, attr.0),
            IrInstr::SetAttr {
                object,
                attr,
                value,
            } => self.emit_set_attr(object, attr.0, value),
            IrInstr::VirtualCall {
                dst,
                receiver,
                receiver_static_type,
                method,
                slot,
                args,
            } => self.emit_virtual_call(*dst, receiver, receiver_static_type, method, slot.0, args),
            IrInstr::StaticCall {
                dst,
                function,
                args,
            } => self.emit_static_call(*dst, function, args),
            IrInstr::BaseCall {
                dst,
                parent_type,
                method,
                args,
            } => self.emit_base_call(*dst, parent_type, method, args),
            IrInstr::NewVector { dst, elements } => {
                self.emit_new_vector(*dst, elements)
            }
            IrInstr::VectorLen { dst, vector } => {
                self.emit_vector_len(*dst, vector)
            }
            IrInstr::VectorPush { vector, value } => {
                self.emit_vector_push(vector, value)
            }
            IrInstr::VectorGet { dst, vector, index } => {
                self.emit_vector_get(*dst, vector, index)
            }
            IrInstr::VectorSet { vector, index, value } => {
                self.emit_vector_set(vector, index, value)
            }
            IrInstr::MakeClosure { dst, function, captures } => {
                self.emit_make_closure(*dst, function, captures)
            }
            IrInstr::ClosureCall { dst, closure, args } => {
                self.emit_closure_call(*dst, closure, args)
            }
            IrInstr::GetCapture { dst, closure, idx, ty } => {
                self.emit_get_capture(*dst, closure.clone(), *idx, ty)
            }
            IrInstr::TypeTest {
                dst,
                value,
                type_name,
            } => self.emit_type_test(*dst, value, type_name),
            IrInstr::TypeCast {
                dst,
                value,
                type_name,
            } => self.emit_type_cast(*dst, value, type_name),
        }
    }

    fn start_label(&mut self, label: LabelId) {
        if !self.block_terminated {
            self.lines.push(format!("  br label %L{}", label.0));
        }
        self.lines.push(format!("L{}:", label.0));
        self.block_terminated = false;
    }

    fn emit_unary(
        &mut self,
        dst: IrPlace,
        op: &IrUnaryOp,
        value: &IrValue,
    ) -> Result<(), LlvmCodegenError> {
        let dst_ty = self.place_type(dst)?;
        match (op, &dst_ty) {
            (IrUnaryOp::Neg, IrTypeRef::Number) => {
                let value = self.read_value_as(value, &IrTypeRef::Number)?;
                let name = self.next_name("neg");
                self.lines
                    .push(format!("  {name} = fneg double {}", value.operand));
                self.store_operand(dst, &dst_ty, &name)
            }
            (IrUnaryOp::Not, IrTypeRef::Boolean) => {
                let value = self.read_value_as(value, &IrTypeRef::Boolean)?;
                let name = self.next_name("not");
                self.lines
                    .push(format!("  {name} = xor i1 {}, true", value.operand));
                self.store_operand(dst, &dst_ty, &name)
            }
            _ => Err(LlvmCodegenError::UnsupportedOperation {
                message: format!("unsupported unary operation {op:?} for {dst_ty}"),
            }),
        }
    }

    fn emit_binary(
        &mut self,
        dst: IrPlace,
        op: &IrBinaryOp,
        left: &IrValue,
        right: &IrValue,
    ) -> Result<(), LlvmCodegenError> {
        let dst_ty = self.place_type(dst)?;
        match op {
            IrBinaryOp::Add
            | IrBinaryOp::Sub
            | IrBinaryOp::Mul
            | IrBinaryOp::Div
            | IrBinaryOp::Mod
            | IrBinaryOp::Pow => self.emit_number_binary(dst, op, left, right, &dst_ty),
            IrBinaryOp::Lt | IrBinaryOp::Le | IrBinaryOp::Gt | IrBinaryOp::Ge => {
                self.emit_number_compare(dst, op, left, right, &dst_ty)
            }
            IrBinaryOp::Eq | IrBinaryOp::Neq => self.emit_equality(dst, op, left, right, &dst_ty),
            IrBinaryOp::And | IrBinaryOp::Or => {
                self.emit_bool_binary(dst, op, left, right, &dst_ty)
            }
            IrBinaryOp::Concat | IrBinaryOp::ConcatSpace => {
                self.emit_string_concat(dst, left, right)
            }
        }
    }

    fn emit_number_binary(
        &mut self,
        dst: IrPlace,
        op: &IrBinaryOp,
        left: &IrValue,
        right: &IrValue,
        dst_ty: &IrTypeRef,
    ) -> Result<(), LlvmCodegenError> {
        if *dst_ty != IrTypeRef::Number {
            return Err(LlvmCodegenError::TypeMismatch {
                expected: IrTypeRef::Number,
                found: dst_ty.clone(),
            });
        }
        let left = self.read_value_as(left, &IrTypeRef::Number)?;
        let right = self.read_value_as(right, &IrTypeRef::Number)?;
        let name = self.next_name("num");
        match op {
            IrBinaryOp::Add => self.lines.push(format!(
                "  {name} = fadd double {}, {}",
                left.operand, right.operand
            )),
            IrBinaryOp::Sub => self.lines.push(format!(
                "  {name} = fsub double {}, {}",
                left.operand, right.operand
            )),
            IrBinaryOp::Mul => self.lines.push(format!(
                "  {name} = fmul double {}, {}",
                left.operand, right.operand
            )),
            IrBinaryOp::Div => self.lines.push(format!(
                "  {name} = fdiv double {}, {}",
                left.operand, right.operand
            )),
            IrBinaryOp::Mod => self.lines.push(format!(
                "  {name} = frem double {}, {}",
                left.operand, right.operand
            )),
            IrBinaryOp::Pow => self.lines.push(format!(
                "  {name} = call double @hulk_pow(double {}, double {})",
                left.operand, right.operand
            )),
            _ => unreachable!("checked by caller"),
        }
        self.store_operand(dst, dst_ty, &name)
    }

    fn emit_number_compare(
        &mut self,
        dst: IrPlace,
        op: &IrBinaryOp,
        left: &IrValue,
        right: &IrValue,
        dst_ty: &IrTypeRef,
    ) -> Result<(), LlvmCodegenError> {
        if *dst_ty != IrTypeRef::Boolean {
            return Err(LlvmCodegenError::TypeMismatch {
                expected: IrTypeRef::Boolean,
                found: dst_ty.clone(),
            });
        }
        let left = self.read_value_as(left, &IrTypeRef::Number)?;
        let right = self.read_value_as(right, &IrTypeRef::Number)?;
        let pred = match op {
            IrBinaryOp::Lt => "olt",
            IrBinaryOp::Le => "ole",
            IrBinaryOp::Gt => "ogt",
            IrBinaryOp::Ge => "oge",
            _ => unreachable!("checked by caller"),
        };
        let name = self.next_name("cmp");
        self.lines.push(format!(
            "  {name} = fcmp {pred} double {}, {}",
            left.operand, right.operand
        ));
        self.store_operand(dst, dst_ty, &name)
    }

    fn emit_equality(
        &mut self,
        dst: IrPlace,
        op: &IrBinaryOp,
        left: &IrValue,
        right: &IrValue,
        dst_ty: &IrTypeRef,
    ) -> Result<(), LlvmCodegenError> {
        if *dst_ty != IrTypeRef::Boolean {
            return Err(LlvmCodegenError::TypeMismatch {
                expected: IrTypeRef::Boolean,
                found: dst_ty.clone(),
            });
        }
        let left_ty = self.value_type(left)?;
        let right_ty = self.value_type(right)?;
        let is_eq = matches!(op, IrBinaryOp::Eq);
        let name = self.next_name("eq");
        match (&left_ty, &right_ty) {
            (IrTypeRef::Number, IrTypeRef::Number) => {
                let left = self.read_value_as(left, &IrTypeRef::Number)?;
                let right = self.read_value_as(right, &IrTypeRef::Number)?;
                let op = if is_eq { "oeq" } else { "one" };
                self.lines.push(format!(
                    "  {name} = fcmp {op} double {}, {}",
                    left.operand, right.operand
                ));
            }
            (IrTypeRef::Boolean, IrTypeRef::Boolean) => {
                let left = self.read_value_as(left, &IrTypeRef::Boolean)?;
                let right = self.read_value_as(right, &IrTypeRef::Boolean)?;
                let op = if is_eq { "eq" } else { "ne" };
                self.lines.push(format!(
                    "  {name} = icmp {op} i1 {}, {}",
                    left.operand, right.operand
                ));
            }
            (IrTypeRef::String, IrTypeRef::String) => {
                let left = self.read_value_as(left, &IrTypeRef::String)?;
                let right = self.read_value_as(right, &IrTypeRef::String)?;
                let raw = self.next_name("streqraw");
                self.lines.push(format!(
                    "  {raw} = call i8 @hulk_string_equals(ptr {}, ptr {})",
                    left.operand, right.operand
                ));
                if is_eq {
                    self.lines.push(format!("  {name} = icmp ne i8 {raw}, 0"));
                } else {
                    let eq = self.next_name("streq");
                    self.lines.push(format!("  {eq} = icmp ne i8 {raw}, 0"));
                    self.lines.push(format!("  {name} = xor i1 {eq}, true"));
                }
            }
            (left_ty, right_ty)
                if is_object_like_type(left_ty) && is_object_like_type(right_ty) =>
            {
                let left = self.read_value_as(left, left_ty)?;
                let right = self.read_value_as(right, right_ty)?;
                let op = if is_eq { "eq" } else { "ne" };
                self.lines.push(format!(
                    "  {name} = icmp {op} ptr {}, {}",
                    left.operand, right.operand
                ));
            }
            (left_ty, right_ty) => {
                return Err(LlvmCodegenError::UnsupportedOperation {
                    message: format!("unsupported equality operand types {left_ty} and {right_ty}"),
                });
            }
        }
        self.store_operand(dst, dst_ty, &name)
    }

    fn emit_bool_binary(
        &mut self,
        dst: IrPlace,
        op: &IrBinaryOp,
        left: &IrValue,
        right: &IrValue,
        dst_ty: &IrTypeRef,
    ) -> Result<(), LlvmCodegenError> {
        if *dst_ty != IrTypeRef::Boolean {
            return Err(LlvmCodegenError::TypeMismatch {
                expected: IrTypeRef::Boolean,
                found: dst_ty.clone(),
            });
        }
        let left = self.read_value_as(left, &IrTypeRef::Boolean)?;
        let right = self.read_value_as(right, &IrTypeRef::Boolean)?;
        let name = self.next_name("bool");
        let instr = match op {
            IrBinaryOp::And => "and",
            IrBinaryOp::Or => "or",
            _ => unreachable!("checked by caller"),
        };
        self.lines.push(format!(
            "  {name} = {instr} i1 {}, {}",
            left.operand, right.operand
        ));
        self.store_operand(dst, dst_ty, &name)
    }

    fn emit_allocate(&mut self, dst: IrPlace, type_name: &str) -> Result<(), LlvmCodegenError> {
        let ty =
            self.types
                .get(type_name)
                .ok_or_else(|| LlvmCodegenError::UnsupportedOperation {
                    message: format!("cannot allocate unknown type '{type_name}'"),
                })?;
        let dst_ty = self.place_type(dst)?;
        match &dst_ty {
            IrTypeRef::User(name) if name == type_name => {}
            IrTypeRef::Object => {}
            other => {
                return Err(LlvmCodegenError::TypeMismatch {
                    expected: IrTypeRef::User(type_name.to_string()),
                    found: other.clone(),
                });
            }
        }

        let result = self.next_name("obj");
        // Basic inheritance uses a flat attribute layout. Child layouts already include
        // inherited attributes, so one allocation with the total count is enough here.
        self.lines.push(format!(
            "  {result} = call ptr @hulk_alloc_object(i64 {}, i64 {}, ptr {})",
            ty.id.0,
            ty.attributes.len(),
            vtable_global_name(type_name)
        ));
        self.store_operand(dst, &dst_ty, &result)
    }

    fn emit_set_attr(
        &mut self,
        object: &IrValue,
        attr_id: u32,
        value: &IrValue,
    ) -> Result<(), LlvmCodegenError> {
        let object = self.read_object_ptr(object)?;
        let attr_id = attr_id as u64;
        match self.value_type(value)? {
            IrTypeRef::Number => {
                let value = self.read_value_as(value, &IrTypeRef::Number)?;
                self.lines.push(format!(
                    "  call void @hulk_object_set_number(ptr {object}, i64 {attr_id}, double {})",
                    value.operand
                ));
            }
            IrTypeRef::Boolean => {
                let value = self.read_value_as(value, &IrTypeRef::Boolean)?;
                let widened = self.next_name("bool8");
                self.lines
                    .push(format!("  {widened} = zext i1 {} to i8", value.operand));
                self.lines.push(format!(
                    "  call void @hulk_object_set_bool(ptr {object}, i64 {attr_id}, i8 {widened})"
                ));
            }
            IrTypeRef::String => {
                let value = self.read_value_as(value, &IrTypeRef::String)?;
                self.lines.push(format!(
                    "  call void @hulk_object_set_string(ptr {object}, i64 {attr_id}, ptr {})",
                    value.operand
                ));
            }
            IrTypeRef::Object | IrTypeRef::User(_) => {
                let value = self.read_object_ptr(value)?;
                self.lines.push(format!(
                    "  call void @hulk_object_set_object(ptr {object}, i64 {attr_id}, ptr {value})"
                ));
            }
            other => {
                return Err(LlvmCodegenError::UnsupportedOperation {
                    message: format!("cannot store attribute value of type {other}"),
                });
            }
        }
        Ok(())
    }

    fn emit_get_attr(
        &mut self,
        dst: IrPlace,
        object: &IrValue,
        attr_id: u32,
    ) -> Result<(), LlvmCodegenError> {
        let object = self.read_object_ptr(object)?;
        let attr_id = attr_id as u64;
        let dst_ty = self.place_type(dst)?;
        match &dst_ty {
            IrTypeRef::Number => {
                let result = self.next_name("attrnum");
                self.lines.push(format!(
                    "  {result} = call double @hulk_object_get_number(ptr {object}, i64 {attr_id})"
                ));
                self.store_operand(dst, &dst_ty, &result)?;
            }
            IrTypeRef::Boolean => {
                let raw = self.next_name("attrbool8");
                self.lines.push(format!(
                    "  {raw} = call i8 @hulk_object_get_bool(ptr {object}, i64 {attr_id})"
                ));
                let result = self.next_name("attrbool");
                self.lines.push(format!("  {result} = icmp ne i8 {raw}, 0"));
                self.store_operand(dst, &dst_ty, &result)?;
            }
            IrTypeRef::String => {
                let result = self.next_name("attrstr");
                self.lines.push(format!(
                    "  {result} = call ptr @hulk_object_get_string(ptr {object}, i64 {attr_id})"
                ));
                self.store_operand(dst, &dst_ty, &result)?;
            }
            IrTypeRef::Object | IrTypeRef::User(_) => {
                let result = self.next_name("attrobj");
                self.lines.push(format!(
                    "  {result} = call ptr @hulk_object_get_object(ptr {object}, i64 {attr_id})"
                ));
                self.store_operand(dst, &dst_ty, &result)?;
            }
            other => {
                return Err(LlvmCodegenError::UnsupportedOperation {
                    message: format!("cannot load attribute as type {other}"),
                });
            }
        }
        Ok(())
    }

    fn emit_type_test(
        &mut self,
        dst: IrPlace,
        value: &IrValue,
        type_name: &str,
    ) -> Result<(), LlvmCodegenError> {
        let dst_ty = self.place_type(dst)?;
        if dst_ty != IrTypeRef::Boolean {
            return Err(LlvmCodegenError::TypeMismatch {
                expected: IrTypeRef::Boolean,
                found: dst_ty,
            });
        }

        let object = self.read_object_ptr(value)?;
        let target_type_id = self.type_id_for_name(type_name)?;
        let raw = self.next_name("israw");
        self.lines.push(format!(
            "  {raw} = call i8 @hulk_object_is(ptr {object}, i64 {target_type_id})"
        ));
        let result = self.next_name("is");
        self.lines.push(format!("  {result} = icmp ne i8 {raw}, 0"));
        self.store_operand(dst, &IrTypeRef::Boolean, &result)
    }

    fn emit_type_cast(
        &mut self,
        dst: IrPlace,
        value: &IrValue,
        type_name: &str,
    ) -> Result<(), LlvmCodegenError> {
        let target_ty = IrTypeRef::User(type_name.to_string());
        let dst_ty = self.place_type(dst)?;
        self.ensure_type(&dst_ty, &target_ty)?;

        let object = self.read_object_ptr(value)?;
        let target_type_id = self.type_id_for_name(type_name)?;
        let result = self.next_name("cast");
        self.lines.push(format!(
            "  {result} = call ptr @hulk_object_as(ptr {object}, i64 {target_type_id})"
        ));
        self.store_operand(dst, &dst_ty, &result)
    }

    fn emit_static_call(
        &mut self,
        dst: Option<IrPlace>,
        function: &str,
        args: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        self.emit_user_call(dst, function, args)
    }

    fn emit_iterable_virtual_call(
        &mut self,
        dst: Option<IrPlace>,
        receiver: &IrValue,
        method: &str,
        slot: u32,
        args: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        // Load the iterable pointer (Object or Iterable IrType)
        let recv_ptr = match self.value_type(receiver)? {
            ty @ (IrTypeRef::Object | IrTypeRef::User(_) | IrTypeRef::Iterable(_)) => {
                let loaded = self.read_value_as(receiver, &ty)?;
                loaded.operand
            }
            other => {
                return Err(LlvmCodegenError::UnsupportedOperation {
                    message: format!("Iterable vcall: expected object-like receiver, found {other}"),
                });
            }
        };

        let fn_ptr = self.next_name("imethod");
        self.lines.push(format!(
            "  {fn_ptr} = call ptr @hulk_object_method(ptr {recv_ptr}, i64 {slot})"
        ));

        match method {
            "next" => {
                // slot 0: int next(ptr self) -> convert to i1 Boolean
                let raw = self.next_name("next_raw");
                self.lines.push(format!("  {raw} = call i32 {fn_ptr}(ptr {recv_ptr})"));
                if let Some(dst) = dst {
                    let b = self.next_name("next_bool");
                    self.lines.push(format!("  {b} = icmp ne i32 {raw}, 0"));
                    self.store_operand(dst, &IrTypeRef::Boolean, &b)?;
                }
            }
            "current" => {
                // Determine element type from the args list or fall back to Number
                let elem_ty = if !args.is_empty() {
                    match self.value_type(&args[0])? {
                        IrTypeRef::Iterable(elem) => *elem,
                        _ => IrTypeRef::Number,
                    }
                } else {
                    IrTypeRef::Number
                };
                // slot 1: double current(ptr self)
                let result = self.next_name("current");
                self.lines.push(format!("  {result} = call double {fn_ptr}(ptr {recv_ptr})"));
                if let Some(dst) = dst {
                    self.store_operand(dst, &elem_ty, &result)?;
                }
            }
            _ => {
                return Err(LlvmCodegenError::UnsupportedOperation {
                    message: format!("unknown Iterable method '{method}'"),
                });
            }
        }
        let _ = args; // already consumed above
        Ok(())
    }

    fn emit_virtual_call(
        &mut self,
        dst: Option<IrPlace>,
        receiver: &IrValue,
        receiver_static_type: &str,
        method: &str,
        slot: u32,
        args: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        // "Iterable" is a built-in protocol (range, vector, user generators).
        // Dispatch through the object vtable at runtime using known slot signatures.
        if receiver_static_type == "Iterable" {
            return self.emit_iterable_virtual_call(dst, receiver, method, slot, args);
        }

        // For protocol/interface types not in self.types, dispatch generically via vtable.
        // Also handle built-in "Vector" (array) type when no user-defined type shadows it.
        if !self.types.contains_key(receiver_static_type) {
            if receiver_static_type == "Vector" {
                return self.emit_vector_method_call(dst, receiver, method, args);
            }
            return self.emit_protocol_virtual_call(dst, receiver, method, slot, args);
        }

        let ty = self.types.get(receiver_static_type).expect("just checked");

        let method_fn = self.resolve_method_function(ty, method, slot)?;
        let sig = self.signatures.get(&method_fn).cloned().ok_or_else(|| {
            LlvmCodegenError::UnknownFunction {
                name: method_fn.clone(),
            }
        })?;
        if sig.params.len() != args.len() {
            return Err(LlvmCodegenError::UnsupportedOperation {
                message: format!(
                    "method '{receiver_static_type}.{method}' expects {} arguments, got {}",
                    sig.params.len(),
                    args.len()
                ),
            });
        }

        let receiver = self.read_object_ptr(receiver)?;
        let function_ptr = self.next_name("vmethod");
        // VirtualCall uses the receiver's runtime vtable. The args list already includes
        // self as its first argument, so the indirect call must not add it again.
        self.lines.push(format!(
            "  {function_ptr} = call ptr @hulk_object_method(ptr {receiver}, i64 {slot})"
        ));

        let mut rendered_args = Vec::new();
        for (arg, expected_ty) in args.iter().zip(&sig.params) {
            let arg = self.read_value_as(arg, expected_ty)?;
            rendered_args.push(format!("{} {}", llvm_type(expected_ty)?, arg.operand));
        }
        let ret_ty = llvm_type(&sig.ret)?;
        let call = format!("call {ret_ty} {function_ptr}({})", rendered_args.join(", "));
        if let Some(dst) = dst {
            let result = self.next_name("vcall");
            self.lines.push(format!("  {result} = {call}"));
            self.store_operand(dst, &sig.ret, &result)?;
        } else {
            self.lines.push(format!("  {call}"));
        }

        Ok(())
    }

    /// Virtual call on a protocol/interface receiver: use hulk_object_method dispatch
    /// and infer argument/return types directly from the IR values.
    fn emit_protocol_virtual_call(
        &mut self,
        dst: Option<IrPlace>,
        receiver: &IrValue,
        method: &str,
        slot: u32,
        args: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        let receiver_ptr = self.read_object_ptr(receiver)?;
        let function_ptr = self.next_name("pmethod");
        self.lines.push(format!(
            "  {function_ptr} = call ptr @hulk_object_method(ptr {receiver_ptr}, i64 {slot})"
        ));

        // Get return type from dst place type (if any), defaulting to ptr.
        let ret_type = if let Some(d) = dst {
            self.place_type(d).unwrap_or(IrTypeRef::Object)
        } else {
            IrTypeRef::Object
        };

        let mut rendered_args = Vec::new();
        for arg in args {
            let arg_ty = self.value_type(arg)?;
            let operand = self.read_value_as(arg, &arg_ty)?;
            rendered_args.push(format!("{} {}", llvm_type(&arg_ty)?, operand.operand));
        }
        let ret_ty_str = llvm_type(&ret_type)?;
        let call = format!("call {ret_ty_str} {function_ptr}({})", rendered_args.join(", "));
        if let Some(d) = dst {
            let result = self.next_name("pvcall");
            self.lines.push(format!("  {result} = {call}"));
            self.store_operand(d, &ret_type, &result)?;
        } else {
            self.lines.push(format!("  {call}"));
        }
        Ok(())
    }

    /// Dispatch Vector built-in methods (size, next, current).
    fn emit_vector_method_call(
        &mut self,
        dst: Option<IrPlace>,
        receiver: &IrValue,
        method: &str,
        args: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        let vec_ptr = self.read_object_ptr(receiver)?;
        match method {
            "size" => {
                let len_i64 = self.next_name("vsize");
                self.lines.push(format!("  {len_i64} = call i64 @hulk_vector_len(ptr {vec_ptr})"));
                let len_f64 = self.next_name("vsize_f");
                self.lines.push(format!("  {len_f64} = sitofp i64 {len_i64} to double"));
                if let Some(dst) = dst {
                    self.store_operand(dst, &IrTypeRef::Number, &len_f64)?;
                }
            }
            "next" => {
                // Returns bool-like (1 or 0); runtime uses int return.
                let n = self.next_name("vnext_i");
                self.lines.push(format!("  {n} = call i64 @hulk_vector_len(ptr {vec_ptr})"));
                // Actually call hulk_vector_next via vtable slot 0
                let fn_ptr = self.next_name("vnext_fn");
                self.lines.push(format!("  {fn_ptr} = call ptr @hulk_object_method(ptr {vec_ptr}, i64 0)"));
                let ret = self.next_name("vnext_ret");
                self.lines.push(format!("  {ret} = call i1 {fn_ptr}(ptr {vec_ptr})"));
                if let Some(dst) = dst {
                    self.store_operand(dst, &IrTypeRef::Boolean, &ret)?;
                }
            }
            "current" => {
                let fn_ptr = self.next_name("vcurr_fn");
                self.lines.push(format!("  {fn_ptr} = call ptr @hulk_object_method(ptr {vec_ptr}, i64 1)"));
                let ret = self.next_name("vcurr_ret");
                let dst_ty = dst.map(|d| self.place_type(d).unwrap_or(IrTypeRef::Number)).unwrap_or(IrTypeRef::Number);
                let ret_ty_str = llvm_type(&dst_ty)?;
                self.lines.push(format!("  {ret} = call {ret_ty_str} {fn_ptr}(ptr {vec_ptr})"));
                if let Some(dst) = dst {
                    self.store_operand(dst, &dst_ty, &ret)?;
                }
            }
            _ => {
                return Err(LlvmCodegenError::UnsupportedOperation {
                    message: format!("unknown Vector method '{method}'"),
                });
            }
        }
        let _ = args;
        Ok(())
    }

    fn emit_new_vector(
        &mut self,
        dst: IrPlace,
        elements: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        let vec_ptr = self.next_name("vec");
        self.lines.push(format!("  {vec_ptr} = call ptr @hulk_vector_new()"));
        for elem in elements {
            let elem_ty = self.value_type(elem)?;
            let as_i64 = self.value_to_i64(elem, &elem_ty)?;
            self.lines.push(format!("  call void @hulk_vector_push(ptr {vec_ptr}, i64 {as_i64})"));
        }
        self.lines.push(format!("  store ptr {vec_ptr}, ptr {}", self.place_ptr(dst)));
        Ok(())
    }

    fn emit_vector_len(
        &mut self,
        dst: IrPlace,
        vector: &IrValue,
    ) -> Result<(), LlvmCodegenError> {
        let vec_ptr = self.read_object_ptr(vector)?;
        let len_i64 = self.next_name("vlen");
        self.lines.push(format!("  {len_i64} = call i64 @hulk_vector_len(ptr {vec_ptr})"));
        // Convert i64 → double (Number)
        let len_f64 = self.next_name("vlen_f");
        self.lines.push(format!("  {len_f64} = sitofp i64 {len_i64} to double"));
        self.store_operand(dst, &IrTypeRef::Number, &len_f64)
    }

    fn emit_vector_push(
        &mut self,
        vector: &IrValue,
        value: &IrValue,
    ) -> Result<(), LlvmCodegenError> {
        let vec_ptr = self.read_object_ptr(vector)?;
        let elem_ty = self.value_type(value)?;
        let as_i64 = self.value_to_i64(value, &elem_ty)?;
        self.lines.push(format!("  call void @hulk_vector_push(ptr {vec_ptr}, i64 {as_i64})"));
        Ok(())
    }

    fn emit_vector_get(
        &mut self,
        dst: IrPlace,
        vector: &IrValue,
        index: &IrValue,
    ) -> Result<(), LlvmCodegenError> {
        let vec_ptr = self.read_object_ptr(vector)?;
        let idx_val = self.read_value_as(index, &IrTypeRef::Number)?;
        let idx_i64 = self.next_name("vidx");
        self.lines.push(format!("  {idx_i64} = fptosi double {} to i64", idx_val.operand));
        let raw = self.next_name("vget_raw");
        self.lines.push(format!("  {raw} = call i64 @hulk_vector_get(ptr {vec_ptr}, i64 {idx_i64})"));
        let dst_ty = self.place_type(dst)?;
        let result = self.i64_to_value(&raw, &dst_ty)?;
        self.store_operand(dst, &dst_ty, &result)
    }

    fn emit_vector_set(
        &mut self,
        vector: &IrValue,
        index: &IrValue,
        value: &IrValue,
    ) -> Result<(), LlvmCodegenError> {
        let vec_ptr = self.read_object_ptr(vector)?;
        let idx_val = self.read_value_as(index, &IrTypeRef::Number)?;
        let idx_i64 = self.next_name("vidx");
        self.lines.push(format!("  {idx_i64} = fptosi double {} to i64", idx_val.operand));
        let elem_ty = self.value_type(value)?;
        let as_i64 = self.value_to_i64(value, &elem_ty)?;
        self.lines.push(format!("  call void @hulk_vector_set(ptr {vec_ptr}, i64 {idx_i64}, i64 {as_i64})"));
        Ok(())
    }

    /// Convert a value of any IR type to i64 for vector storage.
    fn value_to_i64(&mut self, value: &IrValue, ty: &IrTypeRef) -> Result<String, LlvmCodegenError> {
        match ty {
            IrTypeRef::Number => {
                let val = self.read_value_as(value, &IrTypeRef::Number)?;
                let cast = self.next_name("f2i");
                self.lines.push(format!("  {cast} = bitcast double {} to i64", val.operand));
                Ok(cast)
            }
            IrTypeRef::Boolean => {
                let val = self.read_value_as(value, &IrTypeRef::Boolean)?;
                let cast = self.next_name("b2i");
                self.lines.push(format!("  {cast} = zext i1 {} to i64", val.operand));
                Ok(cast)
            }
            IrTypeRef::Object | IrTypeRef::User(_) | IrTypeRef::String
            | IrTypeRef::Vector(_) | IrTypeRef::Iterable(_) | IrTypeRef::Functor { .. } => {
                let val = self.read_object_ptr(value)?;
                let cast = self.next_name("p2i");
                self.lines.push(format!("  {cast} = ptrtoint ptr {val} to i64"));
                Ok(cast)
            }
            IrTypeRef::Unknown => Err(LlvmCodegenError::UnsupportedType { ty: ty.clone() }),
        }
    }

    /// Convert an i64 back to the given IR type.
    fn i64_to_value(&mut self, raw: &str, ty: &IrTypeRef) -> Result<String, LlvmCodegenError> {
        match ty {
            IrTypeRef::Number => {
                let cast = self.next_name("i2f");
                self.lines.push(format!("  {cast} = bitcast i64 {raw} to double"));
                Ok(cast)
            }
            IrTypeRef::Boolean => {
                let cast = self.next_name("i2b");
                self.lines.push(format!("  {cast} = trunc i64 {raw} to i1"));
                Ok(cast)
            }
            IrTypeRef::Object | IrTypeRef::User(_) | IrTypeRef::String
            | IrTypeRef::Vector(_) | IrTypeRef::Iterable(_) | IrTypeRef::Functor { .. } => {
                let cast = self.next_name("i2p");
                self.lines.push(format!("  {cast} = inttoptr i64 {raw} to ptr"));
                Ok(cast)
            }
            IrTypeRef::Unknown => Err(LlvmCodegenError::UnsupportedType { ty: ty.clone() }),
        }
    }

    fn emit_get_capture(
        &mut self,
        dst: IrPlace,
        closure: IrValue,
        idx: usize,
        ty: &IrTypeRef,
    ) -> Result<(), LlvmCodegenError> {
        let closure_ptr = self.read_object_ptr(&closure)?;
        let raw_cap = self.next_name("cap_raw");
        self.lines.push(format!(
            "  {raw_cap} = call ptr @hulk_closure_get_capture(ptr {closure_ptr}, i64 {idx})"
        ));
        // Convert from ptr (stored as inttoptr of bit pattern) to actual type.
        let converted = match ty {
            IrTypeRef::Number => {
                let as_i64 = self.next_name("cap_i64");
                self.lines.push(format!("  {as_i64} = ptrtoint ptr {raw_cap} to i64"));
                let as_f64 = self.next_name("cap_f64");
                self.lines.push(format!("  {as_f64} = bitcast i64 {as_i64} to double"));
                as_f64
            }
            IrTypeRef::Boolean => {
                let as_i64 = self.next_name("cap_i64");
                self.lines.push(format!("  {as_i64} = ptrtoint ptr {raw_cap} to i64"));
                let as_i1 = self.next_name("cap_i1");
                self.lines.push(format!("  {as_i1} = trunc i64 {as_i64} to i1"));
                as_i1
            }
            _ => raw_cap,
        };
        self.store_operand(dst, ty, &converted)
    }

    fn emit_make_closure(
        &mut self,
        dst: IrPlace,
        function: &str,
        captures: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        // Look up the LLVM function name from signatures.
        let llvm_fn_name = self.signatures.get(function)
            .map(|sig| sig.llvm_name.clone())
            .ok_or_else(|| LlvmCodegenError::UnknownFunction { name: function.to_string() })?;
        let num_captures = captures.len() as u64;
        let closure_ptr = self.next_name("closure");
        self.lines.push(format!(
            "  {closure_ptr} = call ptr @hulk_closure_alloc(ptr @{llvm_fn_name}, i64 {num_captures})"
        ));
        for (idx, cap) in captures.iter().enumerate() {
            let cap_ty = self.value_type(cap)?;
            let as_i64 = self.value_to_i64(cap, &cap_ty)?;
            // Store as ptr via ptrtoint first, then inttoptr
            let as_ptr = self.next_name("cap_ptr");
            self.lines.push(format!("  {as_ptr} = inttoptr i64 {as_i64} to ptr"));
            self.lines.push(format!(
                "  call void @hulk_closure_set_capture(ptr {closure_ptr}, i64 {idx}, ptr {as_ptr})"
            ));
        }
        self.store_operand(dst, &IrTypeRef::Object, &closure_ptr)
    }

    fn emit_closure_call(
        &mut self,
        dst: Option<IrPlace>,
        closure: &IrValue,
        args: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        let closure_ty = self.value_type(closure)?;
        let (param_types, ret_type) = match &closure_ty {
            IrTypeRef::Functor { params, ret, .. } => (params.clone(), *ret.clone()),
            _ => return Err(LlvmCodegenError::UnsupportedOperation {
                message: format!("ClosureCall on non-functor type: {closure_ty:?}"),
            }),
        };

        // Load the function pointer from the closure struct (first field).
        let closure_ptr = self.read_object_ptr(closure)?;
        let fn_ptr = self.next_name("fn_ptr");
        self.lines.push(format!("  {fn_ptr} = load ptr, ptr {closure_ptr}"));

        // New calling convention: always pass the closure itself as the first arg,
        // then the explicit user args. The lambda extracts captures from the closure.
        let mut rendered_args = vec![format!("ptr {closure_ptr}")];

        // Explicit args.
        for (arg, expected_ty) in args.iter().zip(param_types.iter()) {
            let arg = self.read_value_as(arg, expected_ty)?;
            rendered_args.push(format!("{} {}", llvm_type(expected_ty)?, arg.operand));
        }

        let ret_ty_str = llvm_type(&ret_type)?;
        let call = format!("call {ret_ty_str} {fn_ptr}({})", rendered_args.join(", "));
        if let Some(dst) = dst {
            let result = self.next_name("cresult");
            self.lines.push(format!("  {result} = {call}"));
            self.store_operand(dst, &ret_type, &result)?;
        } else {
            self.lines.push(format!("  {call}"));
        }
        Ok(())
    }

    fn emit_base_call(
        &mut self,
        dst: Option<IrPlace>,
        parent_type: &str,
        method: &str,
        args: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        let ty =
            self.types
                .get(parent_type)
                .ok_or_else(|| LlvmCodegenError::UnsupportedOperation {
                    message: format!(
                        "cannot emit base call '{method}' for unknown parent type '{parent_type}'"
                    ),
                })?;
        // base() stays a direct parent call; it deliberately bypasses vtable dispatch.
        let method_fn = self.resolve_method_function(ty, method, 0)?;
        self.emit_user_call(dst, &method_fn, args)
    }

    fn emit_string_concat(
        &mut self,
        dst: IrPlace,
        left: &IrValue,
        right: &IrValue,
    ) -> Result<(), LlvmCodegenError> {
        let dst_ty = self.place_type(dst)?;
        if dst_ty != IrTypeRef::String {
            return Err(LlvmCodegenError::TypeMismatch {
                expected: IrTypeRef::String,
                found: dst_ty,
            });
        }

        let left = self.read_value_as_string(left)?;
        let right = self.read_value_as_string(right)?;
        let result = self.next_name("concat");
        self.lines.push(format!(
            "  {result} = call ptr @hulk_string_concat(ptr {left}, ptr {right})"
        ));
        self.store_operand(dst, &IrTypeRef::String, &result)
    }

    fn emit_call(
        &mut self,
        dst: Option<IrPlace>,
        function: &str,
        args: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        match function {
            "print" => self.emit_print_call(dst, args),
            "sqrt" | "sin" | "cos" | "exp" | "log" | "rand" => {
                self.emit_math_builtin(dst, function, args)
            }
            "range" => self.emit_range_builtin(dst, args),
            name => self.emit_user_call(dst, name, args),
        }
    }

    fn emit_print_call(
        &mut self,
        dst: Option<IrPlace>,
        args: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        if args.len() != 1 {
            return Err(LlvmCodegenError::UnsupportedOperation {
                message: "print expects one argument".to_string(),
            });
        }
        let arg_ty = self.value_type(&args[0])?;
        match arg_ty {
            IrTypeRef::Number => {
                let arg = self.read_value_as(&args[0], &IrTypeRef::Number)?;
                self.lines.push(format!(
                    "  call void @hulk_print_number(double {})",
                    arg.operand
                ));
            }
            IrTypeRef::Boolean => {
                let arg = self.read_value_as(&args[0], &IrTypeRef::Boolean)?;
                let widened = self.next_name("bool8");
                self.lines
                    .push(format!("  {widened} = zext i1 {} to i8", arg.operand));
                self.lines
                    .push(format!("  call void @hulk_print_bool(i8 {widened})"));
            }
            IrTypeRef::String => {
                let arg = self.read_value_as(&args[0], &IrTypeRef::String)?;
                self.lines.push(format!(
                    "  call void @hulk_print_string(ptr {})",
                    arg.operand
                ));
            }
            other => {
                return Err(LlvmCodegenError::UnsupportedOperation {
                    message: format!("print for {other} is not implemented in the minimal backend"),
                });
            }
        }

        if let Some(dst) = dst {
            self.store_default(dst)?;
        }
        Ok(())
    }

    fn emit_math_builtin(
        &mut self,
        dst: Option<IrPlace>,
        function: &str,
        args: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        let runtime_name = match function {
            "sqrt" => "hulk_sqrt",
            "sin" => "hulk_sin",
            "cos" => "hulk_cos",
            "exp" => "hulk_exp",
            "log" => "hulk_log",
            "rand" => "hulk_rand",
            _ => unreachable!("checked by caller"),
        };
        let expected_arity = if function == "rand" {
            0
        } else if function == "log" {
            2
        } else {
            1
        };
        if args.len() != expected_arity {
            return Err(LlvmCodegenError::UnsupportedOperation {
                message: format!("{function} expects {expected_arity} arguments"),
            });
        }
        let mut rendered_args = Vec::new();
        for arg in args {
            let arg = self.read_value_as(arg, &IrTypeRef::Number)?;
            rendered_args.push(format!("double {}", arg.operand));
        }
        let result = self.next_name(function);
        self.lines.push(format!(
            "  {result} = call double @{runtime_name}({})",
            rendered_args.join(", ")
        ));
        if let Some(dst) = dst {
            self.store_operand(dst, &IrTypeRef::Number, &result)?;
        }
        Ok(())
    }

    fn emit_range_builtin(
        &mut self,
        dst: Option<IrPlace>,
        args: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        if args.len() != 2 {
            return Err(LlvmCodegenError::UnsupportedOperation {
                message: "range expects 2 arguments".to_string(),
            });
        }
        let start = self.read_value_as(&args[0], &IrTypeRef::Number)?;
        let end = self.read_value_as(&args[1], &IrTypeRef::Number)?;
        let result = self.next_name("range");
        self.lines.push(format!(
            "  {result} = call ptr @hulk_range(double {}, double {})",
            start.operand, end.operand
        ));
        if let Some(dst) = dst {
            let dst_ty = self.place_type(dst)?;
            self.store_operand(dst, &dst_ty, &result)?;
        }
        Ok(())
    }

    fn emit_user_call(
        &mut self,
        dst: Option<IrPlace>,
        function: &str,
        args: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        let sig = self.signatures.get(function).cloned().ok_or_else(|| {
            LlvmCodegenError::UnknownFunction {
                name: function.to_string(),
            }
        })?;
        if sig.params.len() != args.len() {
            return Err(LlvmCodegenError::UnsupportedOperation {
                message: format!(
                    "function '{function}' expects {} arguments, got {}",
                    sig.params.len(),
                    args.len()
                ),
            });
        }
        let mut rendered_args = Vec::new();
        for (arg, expected_ty) in args.iter().zip(&sig.params) {
            let arg = self.read_value_as(arg, expected_ty)?;
            rendered_args.push(format!("{} {}", llvm_type(expected_ty)?, arg.operand));
        }
        let ret_ty = llvm_type(&sig.ret)?;
        let call = format!(
            "call {ret_ty} @{}({})",
            sig.llvm_name,
            rendered_args.join(", ")
        );
        if let Some(dst) = dst {
            let result = self.next_name("call");
            self.lines.push(format!("  {result} = {call}"));
            self.store_operand(dst, &sig.ret, &result)?;
        } else {
            self.lines.push(format!("  {call}"));
        }
        Ok(())
    }

    fn emit_return(&mut self, value: Option<&IrValue>) -> Result<(), LlvmCodegenError> {
        if let Some(value) = value {
            let ret_ty = self.function.return_type.clone();
            let value = self.read_value_as(value, &ret_ty)?;
            self.lines
                .push(format!("  ret {} {}", llvm_type(&ret_ty)?, value.operand));
        } else {
            return Err(LlvmCodegenError::UnsupportedOperation {
                message: "return without value is not supported for non-void LLVM functions"
                    .to_string(),
            });
        }
        self.block_terminated = true;
        Ok(())
    }

    fn store_value(&mut self, dst: IrPlace, src: &IrValue) -> Result<(), LlvmCodegenError> {
        let dst_ty = self.place_type(dst)?;
        let src = self.read_value_as(src, &dst_ty)?;
        self.store_operand(dst, &dst_ty, &src.operand)
    }

    fn store_default(&mut self, dst: IrPlace) -> Result<(), LlvmCodegenError> {
        let dst_ty = self.place_type(dst)?;
        let default = default_value(&dst_ty)?;
        self.store_operand(dst, &dst_ty, &default)
    }

    fn store_operand(
        &mut self,
        dst: IrPlace,
        ty: &IrTypeRef,
        operand: &str,
    ) -> Result<(), LlvmCodegenError> {
        self.lines.push(format!(
            "  store {} {operand}, ptr {}",
            llvm_type(ty)?,
            self.place_ptr(dst)
        ));
        Ok(())
    }

    fn read_value_as(
        &mut self,
        value: &IrValue,
        expected_ty: &IrTypeRef,
    ) -> Result<TypedOperand, LlvmCodegenError> {
        match value {
            IrValue::Temp(id) => {
                let ty = self.temp_types.get(id).cloned().ok_or_else(|| {
                    LlvmCodegenError::UnknownValue {
                        name: format!("%t{}", id.0),
                    }
                })?;
                self.ensure_type(expected_ty, &ty)?;
                let name = self.next_name("load");
                self.lines.push(format!(
                    "  {name} = load {}, ptr %t{}.addr",
                    llvm_type(&ty)?,
                    id.0
                ));
                Ok(TypedOperand { operand: name, ty })
            }
            IrValue::Local(id) => {
                let ty = self.local_types.get(id).cloned().ok_or_else(|| {
                    LlvmCodegenError::UnknownValue {
                        name: format!("%l{}", id.0),
                    }
                })?;
                self.ensure_type(expected_ty, &ty)?;
                let name = self.next_name("load");
                self.lines.push(format!(
                    "  {name} = load {}, ptr %l{}.addr",
                    llvm_type(&ty)?,
                    id.0
                ));
                Ok(TypedOperand { operand: name, ty })
            }
            IrValue::Param(id) => {
                let ty = self.param_types.get(id).cloned().ok_or_else(|| {
                    LlvmCodegenError::UnknownValue {
                        name: format!("%p{}", id.0),
                    }
                })?;
                self.ensure_type(expected_ty, &ty)?;
                Ok(TypedOperand {
                    operand: format!("%p{}", id.0),
                    ty,
                })
            }
            IrValue::ConstNumber(value) => {
                self.ensure_type(expected_ty, &IrTypeRef::Number)?;
                Ok(TypedOperand {
                    operand: llvm_float(*value),
                    ty: IrTypeRef::Number,
                })
            }
            IrValue::ConstBool(value) => {
                self.ensure_type(expected_ty, &IrTypeRef::Boolean)?;
                Ok(TypedOperand {
                    operand: value.to_string(),
                    ty: IrTypeRef::Boolean,
                })
            }
            IrValue::Null | IrValue::Unit => Ok(TypedOperand {
                operand: default_value(expected_ty)?,
                ty: expected_ty.clone(),
            }),
            IrValue::DataRef(id) => self.read_data_ref(*id, expected_ty),
        }
    }

    fn read_value_as_string(&mut self, value: &IrValue) -> Result<String, LlvmCodegenError> {
        match self.value_type(value)? {
            IrTypeRef::String => {
                let value = self.read_value_as(value, &IrTypeRef::String)?;
                Ok(value.operand)
            }
            IrTypeRef::Number => {
                let value = self.read_value_as(value, &IrTypeRef::Number)?;
                let result = self.next_name("strnum");
                self.lines.push(format!(
                    "  {result} = call ptr @hulk_string_from_number(double {})",
                    value.operand
                ));
                Ok(result)
            }
            IrTypeRef::Boolean => {
                let value = self.read_value_as(value, &IrTypeRef::Boolean)?;
                let widened = self.next_name("bool8");
                self.lines
                    .push(format!("  {widened} = zext i1 {} to i8", value.operand));
                let result = self.next_name("strbool");
                self.lines.push(format!(
                    "  {result} = call ptr @hulk_string_from_bool(i8 {widened})"
                ));
                Ok(result)
            }
            other => Err(LlvmCodegenError::UnsupportedOperation {
                message: format!("cannot concatenate value of type {other} as a string"),
            }),
        }
    }

    fn read_object_ptr(&mut self, value: &IrValue) -> Result<String, LlvmCodegenError> {
        match self.value_type(value)? {
            ty @ (IrTypeRef::Object
            | IrTypeRef::User(_)
            | IrTypeRef::Vector(_)
            | IrTypeRef::Iterable(_)
            | IrTypeRef::Functor { .. }) => {
                let value = self.read_value_as(value, &ty)?;
                Ok(value.operand)
            }
            other => Err(LlvmCodegenError::UnsupportedOperation {
                message: format!("expected object pointer, found {other}"),
            }),
        }
    }

    fn value_type(&self, value: &IrValue) -> Result<IrTypeRef, LlvmCodegenError> {
        match value {
            IrValue::Temp(id) => {
                self.temp_types
                    .get(id)
                    .cloned()
                    .ok_or_else(|| LlvmCodegenError::UnknownValue {
                        name: format!("%t{}", id.0),
                    })
            }
            IrValue::Local(id) => {
                self.local_types
                    .get(id)
                    .cloned()
                    .ok_or_else(|| LlvmCodegenError::UnknownValue {
                        name: format!("%l{}", id.0),
                    })
            }
            IrValue::Param(id) => {
                self.param_types
                    .get(id)
                    .cloned()
                    .ok_or_else(|| LlvmCodegenError::UnknownValue {
                        name: format!("%p{}", id.0),
                    })
            }
            IrValue::ConstNumber(_) => Ok(IrTypeRef::Number),
            IrValue::ConstBool(_) => Ok(IrTypeRef::Boolean),
            IrValue::Null => Ok(IrTypeRef::Object),
            IrValue::Unit => Ok(IrTypeRef::Object),
            IrValue::DataRef(id) => self.data_type(*id),
        }
    }

    fn read_data_ref(
        &self,
        id: DataId,
        expected_ty: &IrTypeRef,
    ) -> Result<TypedOperand, LlvmCodegenError> {
        let data = self
            .data
            .get(&id)
            .ok_or(LlvmCodegenError::MissingData { id })?;
        match &data.value {
            IrDataValue::String(_) => {
                self.ensure_type(expected_ty, &IrTypeRef::String)?;
                Ok(TypedOperand {
                    operand: format!("@str_{}", id.0),
                    ty: IrTypeRef::String,
                })
            }
            IrDataValue::Number(_) | IrDataValue::Boolean(_) => {
                Err(LlvmCodegenError::UnsupportedInstruction {
                    instruction: "DataRef",
                })
            }
        }
    }

    fn data_type(&self, id: DataId) -> Result<IrTypeRef, LlvmCodegenError> {
        let data = self
            .data
            .get(&id)
            .ok_or(LlvmCodegenError::MissingData { id })?;
        match &data.value {
            IrDataValue::String(_) => Ok(IrTypeRef::String),
            IrDataValue::Number(_) | IrDataValue::Boolean(_) => {
                Err(LlvmCodegenError::UnsupportedInstruction {
                    instruction: "DataRef",
                })
            }
        }
    }

    fn place_type(&self, place: IrPlace) -> Result<IrTypeRef, LlvmCodegenError> {
        match place {
            IrPlace::Temp(id) => {
                self.temp_types
                    .get(&id)
                    .cloned()
                    .ok_or_else(|| LlvmCodegenError::UnknownValue {
                        name: format!("%t{}", id.0),
                    })
            }
            IrPlace::Local(id) => {
                self.local_types
                    .get(&id)
                    .cloned()
                    .ok_or_else(|| LlvmCodegenError::UnknownValue {
                        name: format!("%l{}", id.0),
                    })
            }
        }
    }

    fn place_ptr(&self, place: IrPlace) -> String {
        match place {
            IrPlace::Temp(id) => format!("%t{}.addr", id.0),
            IrPlace::Local(id) => format!("%l{}.addr", id.0),
        }
    }

    fn resolve_method_function(
        &self,
        ty: &IrType,
        method: &str,
        slot: u32,
    ) -> Result<String, LlvmCodegenError> {
        ty.methods
            .iter()
            .find(|candidate| candidate.name == method)
            .or_else(|| ty.methods.iter().find(|candidate| candidate.slot.0 == slot))
            .map(|candidate| candidate.function.clone())
            .ok_or_else(|| LlvmCodegenError::UnsupportedOperation {
                message: format!(
                    "cannot resolve method '{method}' on concrete type '{}'",
                    ty.name
                ),
            })
    }

    fn type_id_for_name(&self, type_name: &str) -> Result<u32, LlvmCodegenError> {
        self.types.get(type_name).map(|ty| ty.id.0).ok_or_else(|| {
            LlvmCodegenError::UnsupportedOperation {
                message: format!("unknown type '{type_name}' in runtime type operation"),
            }
        })
    }

    fn is_descendant_of(&self, child: &str, ancestor: &str) -> bool {
        let mut current = self.types.get(child).and_then(|ty| ty.parent.as_deref());
        while let Some(name) = current {
            if name == ancestor {
                return true;
            }
            current = self.types.get(name).and_then(|ty| ty.parent.as_deref());
        }
        false
    }

    fn ensure_type(&self, expected: &IrTypeRef, found: &IrTypeRef) -> Result<(), LlvmCodegenError> {
        if self.is_assignable_to(expected, found) {
            Ok(())
        } else {
            Err(LlvmCodegenError::TypeMismatch {
                expected: expected.clone(),
                found: found.clone(),
            })
        }
    }

    fn is_assignable_to(&self, expected: &IrTypeRef, found: &IrTypeRef) -> bool {
        if expected == found {
            return true;
        }

        // All pointer-typed IR values (Object, User, Iterable) compile to `ptr`
        // in LLVM IR and can be passed between each other freely.
        let is_ptr = |ty: &IrTypeRef| {
            matches!(
                ty,
                IrTypeRef::Object | IrTypeRef::User(_) | IrTypeRef::Iterable(_)
            )
        };
        if is_ptr(expected) && is_ptr(found) {
            return true;
        }

        // Functors are assignable if they have compatible param/ret types (num_captures may differ)
        let is_ptr_like = |ty: &IrTypeRef| {
            matches!(
                ty,
                IrTypeRef::Object | IrTypeRef::User(_) | IrTypeRef::Iterable(_) | IrTypeRef::Functor { .. } | IrTypeRef::Vector(_)
            )
        };
        if is_ptr_like(expected) && is_ptr_like(found) {
            return true;
        }

        match (expected, found) {
            (IrTypeRef::Object, IrTypeRef::User(_)) => true,
            (IrTypeRef::User(expected), IrTypeRef::User(found)) => {
                self.is_descendant_of(found, expected)
            }
            _ => false,
        }
    }

    fn next_name(&mut self, prefix: &str) -> String {
        let id = self.next_value_id;
        self.next_value_id += 1;
        format!("%{prefix}.{id}")
    }
}

#[derive(Debug, Clone)]
struct TypedOperand {
    operand: String,
    #[allow(dead_code)]
    ty: IrTypeRef,
}

fn llvm_function_name(function: &IrFunction) -> String {
    if function.name == "entry" {
        "hulk_entry".to_string()
    } else {
        sanitize_symbol(&function.name)
    }
}

fn sanitize_symbol(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' || ch == '.' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn vtable_global_name(type_name: &str) -> String {
    format!("@{}_vtable", sanitize_symbol(type_name))
}

fn vtable_methods_global_name(type_name: &str) -> String {
    format!("@{}_vtable_methods", sanitize_symbol(type_name))
}

fn llvm_type(ty: &IrTypeRef) -> Result<&'static str, LlvmCodegenError> {
    match ty {
        IrTypeRef::Number => Ok("double"),
        IrTypeRef::Boolean => Ok("i1"),
        IrTypeRef::Object
        | IrTypeRef::User(_)
        | IrTypeRef::String
        | IrTypeRef::Vector(_)
        | IrTypeRef::Iterable(_)
        | IrTypeRef::Functor { .. } => Ok("ptr"),
        IrTypeRef::Unknown => Err(LlvmCodegenError::UnsupportedType { ty: ty.clone() }),
    }
}

fn default_value(ty: &IrTypeRef) -> Result<String, LlvmCodegenError> {
    match ty {
        IrTypeRef::Number => Ok("0.0".to_string()),
        IrTypeRef::Boolean => Ok("false".to_string()),
        IrTypeRef::Object
        | IrTypeRef::User(_)
        | IrTypeRef::String
        | IrTypeRef::Vector(_)
        | IrTypeRef::Iterable(_)
        | IrTypeRef::Functor { .. } => Ok("null".to_string()),
        IrTypeRef::Unknown => Err(LlvmCodegenError::UnsupportedType { ty: ty.clone() }),
    }
}

fn is_object_like_type(ty: &IrTypeRef) -> bool {
    matches!(ty, IrTypeRef::Object | IrTypeRef::User(_))
}

fn llvm_float(value: f64) -> String {
    if value.fract() == 0.0 {
        format!("{value:.1}")
    } else {
        value.to_string()
    }
}

fn llvm_string_bytes(bytes: &[u8]) -> String {
    let mut escaped = String::with_capacity(bytes.len() * 4 + 4);
    for byte in bytes {
        escaped.push_str(&format!("\\{:02X}", byte));
    }
    escaped.push_str("\\00");
    escaped
}

#[cfg(test)]
mod tests {
    use super::*;
    use hulk_ir::{
        DataId, FunctionId, IrBinaryOp, IrData, IrDataValue, IrFunction, IrFunctionKind, IrInstr,
        IrParam, IrPlace, IrProgram, IrTemp, IrTypeRef, IrValue, ParamId, TempId,
    };

    #[test]
    fn emits_minimal_print_program() {
        let program = IrProgram {
            types: vec![],
            data: vec![],
            functions: vec![IrFunction {
                id: FunctionId(0),
                name: "entry".to_string(),
                kind: IrFunctionKind::Entry,
                params: vec![],
                locals: vec![],
                temps: vec![
                    IrTemp {
                        id: TempId(0),
                        ty: IrTypeRef::Number,
                    },
                    IrTemp {
                        id: TempId(1),
                        ty: IrTypeRef::Object,
                    },
                ],
                return_type: IrTypeRef::Object,
                body: vec![
                    IrInstr::Binary {
                        dst: IrPlace::Temp(TempId(0)),
                        op: IrBinaryOp::Add,
                        left: IrValue::ConstNumber(2.0),
                        right: IrValue::ConstNumber(3.0),
                    },
                    IrInstr::Call {
                        dst: Some(IrPlace::Temp(TempId(1))),
                        function: "print".to_string(),
                        args: vec![IrValue::Temp(TempId(0))],
                    },
                    IrInstr::Return(Some(IrValue::Temp(TempId(1)))),
                ],
            }],
            entry: FunctionId(0),
        };

        let llvm = emit_llvm(&program).expect("codegen should pass");
        assert!(llvm.contains("declare void @hulk_print_number(double)"));
        assert!(llvm.contains("define ptr @hulk_entry()"));
        assert!(llvm.contains("fadd double 2.0, 3.0"));
        assert!(llvm.contains("call void @hulk_print_number(double"));
        assert!(llvm.contains("define i32 @main()"));
    }

    #[test]
    fn emits_user_function_call() {
        let program = IrProgram {
            types: vec![],
            data: vec![],
            functions: vec![
                IrFunction {
                    id: FunctionId(0),
                    name: "entry".to_string(),
                    kind: IrFunctionKind::Entry,
                    params: vec![],
                    locals: vec![],
                    temps: vec![IrTemp {
                        id: TempId(0),
                        ty: IrTypeRef::Number,
                    }],
                    return_type: IrTypeRef::Number,
                    body: vec![
                        IrInstr::Call {
                            dst: Some(IrPlace::Temp(TempId(0))),
                            function: "id".to_string(),
                            args: vec![IrValue::ConstNumber(4.0)],
                        },
                        IrInstr::Return(Some(IrValue::Temp(TempId(0)))),
                    ],
                },
                IrFunction {
                    id: FunctionId(1),
                    name: "id".to_string(),
                    kind: IrFunctionKind::Function,
                    params: vec![IrParam {
                        id: ParamId(0),
                        name: "x".to_string(),
                        ty: IrTypeRef::Number,
                    }],
                    locals: vec![],
                    temps: vec![],
                    return_type: IrTypeRef::Number,
                    body: vec![IrInstr::Return(Some(IrValue::Param(ParamId(0))))],
                },
            ],
            entry: FunctionId(0),
        };

        let llvm = emit_llvm(&program).expect("codegen should pass");
        assert!(llvm.contains("define double @id(double %p0)"));
        assert!(llvm.contains("call double @id(double 4.0)"));
    }

    #[test]
    fn emits_static_string_data_and_print_string() {
        let program = IrProgram {
            types: vec![],
            data: vec![IrData {
                id: DataId(0),
                value: IrDataValue::String("Hello".to_string()),
            }],
            functions: vec![IrFunction {
                id: FunctionId(0),
                name: "entry".to_string(),
                kind: IrFunctionKind::Entry,
                params: vec![],
                locals: vec![],
                temps: vec![IrTemp {
                    id: TempId(0),
                    ty: IrTypeRef::Object,
                }],
                return_type: IrTypeRef::Object,
                body: vec![
                    IrInstr::Call {
                        dst: Some(IrPlace::Temp(TempId(0))),
                        function: "print".to_string(),
                        args: vec![IrValue::DataRef(DataId(0))],
                    },
                    IrInstr::Return(Some(IrValue::Temp(TempId(0)))),
                ],
            }],
            entry: FunctionId(0),
        };

        let llvm = emit_llvm(&program).expect("codegen should pass");
        assert!(llvm.contains("%HulkString = type { i64, ptr }"));
        assert!(llvm.contains("@str_0_data = private unnamed_addr constant [6 x i8]"));
        assert!(llvm.contains("call void @hulk_print_string(ptr @str_0)"));
    }

    #[test]
    fn escapes_string_bytes_in_global_data() {
        let program = IrProgram {
            types: vec![],
            data: vec![IrData {
                id: DataId(0),
                value: IrDataValue::String("A\nB".to_string()),
            }],
            functions: vec![IrFunction {
                id: FunctionId(0),
                name: "entry".to_string(),
                kind: IrFunctionKind::Entry,
                params: vec![],
                locals: vec![],
                temps: vec![IrTemp {
                    id: TempId(0),
                    ty: IrTypeRef::Object,
                }],
                return_type: IrTypeRef::Object,
                body: vec![
                    IrInstr::Call {
                        dst: Some(IrPlace::Temp(TempId(0))),
                        function: "print".to_string(),
                        args: vec![IrValue::DataRef(DataId(0))],
                    },
                    IrInstr::Return(Some(IrValue::Temp(TempId(0)))),
                ],
            }],
            entry: FunctionId(0),
        };

        let llvm = emit_llvm(&program).expect("codegen should pass");
        assert!(llvm.contains("\\41\\0A\\42\\00"));
    }
}
