use hulk_ir::{
    DataId, FunctionId, IrBinaryOp, IrData, IrDataValue, IrFunction, IrInstr, IrPlace, IrProgram,
    IrTypeRef, IrUnaryOp, IrValue, LabelId, LocalId, ParamId, TempId,
};
use std::collections::HashMap;
use std::fmt;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LlvmCodegenError {
    UnsupportedType {
        ty: IrTypeRef,
    },
    UnsupportedInstruction {
        instruction: &'static str,
    },
    UnsupportedOperation {
        message: String,
    },
    UnknownFunction {
        name: String,
    },
    UnknownValue {
        name: String,
    },
    MissingData {
        id: DataId,
    },
    TypeMismatch {
        expected: IrTypeRef,
        found: IrTypeRef,
    },
    MissingEntry {
        id: FunctionId,
    },
}

impl fmt::Display for LlvmCodegenError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            LlvmCodegenError::UnsupportedType { ty } => {
                write!(f, "unsupported type for LLVM codegen: {ty}")
            }
            LlvmCodegenError::UnsupportedInstruction { instruction } => {
                write!(
                    f,
                    "unsupported IR instruction for LLVM codegen: {instruction}"
                )
            }
            LlvmCodegenError::UnsupportedOperation { message } => write!(f, "{message}"),
            LlvmCodegenError::UnknownFunction { name } => write!(f, "unknown function '{name}'"),
            LlvmCodegenError::UnknownValue { name } => write!(f, "unknown value '{name}'"),
            LlvmCodegenError::MissingData { id } => {
                write!(f, "IR static data #{} was not found", id.0)
            }
            LlvmCodegenError::TypeMismatch { expected, found } => {
                write!(f, "type mismatch: expected {expected}, found {found}")
            }
            LlvmCodegenError::MissingEntry { id } => {
                write!(f, "IR entry function #{} was not found", id.0)
            }
        }
    }
}

impl std::error::Error for LlvmCodegenError {}

pub fn emit_llvm(program: &IrProgram) -> Result<String, LlvmCodegenError> {
    LlvmEmitter::new(program).emit_program()
}

#[derive(Debug, Clone)]
struct FunctionSig {
    llvm_name: String,
    params: Vec<IrTypeRef>,
    ret: IrTypeRef,
}

struct LlvmEmitter<'a> {
    program: &'a IrProgram,
    signatures: HashMap<String, FunctionSig>,
    data: HashMap<DataId, &'a IrData>,
}

impl<'a> LlvmEmitter<'a> {
    fn new(program: &'a IrProgram) -> Self {
        let mut signatures = HashMap::new();
        for function in &program.functions {
            signatures.insert(
                function.name.clone(),
                FunctionSig {
                    llvm_name: llvm_function_name(function),
                    params: function
                        .params
                        .iter()
                        .map(|param| param.ty.clone())
                        .collect(),
                    ret: function.return_type.clone(),
                },
            );
        }
        let data = program
            .data
            .iter()
            .map(|item| (item.id, item))
            .collect::<HashMap<_, _>>();
        Self {
            program,
            signatures,
            data,
        }
    }

    fn emit_program(&self) -> Result<String, LlvmCodegenError> {
        if !self
            .program
            .functions
            .iter()
            .any(|function| function.id == self.program.entry)
        {
            return Err(LlvmCodegenError::MissingEntry {
                id: self.program.entry,
            });
        }

        let mut out = String::new();
        out.push_str("; generated by hulk-codegen-llvm\n");
        out.push_str("declare void @hulk_print_number(double)\n");
        out.push_str("declare void @hulk_print_bool(i8)\n");
        out.push_str("declare double @hulk_sqrt(double)\n");
        out.push_str("declare double @hulk_sin(double)\n");
        out.push_str("declare double @hulk_cos(double)\n");
        out.push_str("declare double @hulk_exp(double)\n");
        out.push_str("declare double @hulk_log(double, double)\n");
        out.push_str("declare double @hulk_pow(double, double)\n");
        out.push_str("declare double @hulk_rand()\n");
        out.push_str("declare void @hulk_print_string(ptr)\n");
        out.push('\n');
        self.emit_data(&mut out)?;

        for function in &self.program.functions {
            FunctionEmitter::new(function, &self.signatures, &self.data).emit(&mut out)?;
            out.push('\n');
        }

        self.emit_main(&mut out)?;
        Ok(out)
    }

    fn emit_data(&self, out: &mut String) -> Result<(), LlvmCodegenError> {
        out.push_str("%HulkString = type { i64, ptr }\n\n");
        for data in &self.program.data {
            match &data.value {
                IrDataValue::String(value) => {
                    let base_name = format!("str_{}", data.id.0);
                    let byte_name = format!("@{}_data", base_name);
                    let desc_name = format!("@{}", base_name);
                    let bytes = llvm_string_bytes(value.as_bytes());
                    out.push_str(&format!(
                        "{byte_name} = private unnamed_addr constant [{} x i8] c\"{bytes}\"\n",
                        value.as_bytes().len() + 1
                    ));
                    out.push_str(&format!(
                        "{desc_name} = private unnamed_addr constant %HulkString {{ i64 {}, ptr {byte_name} }}\n",
                        value.as_bytes().len()
                    ));
                }
                IrDataValue::Number(_) | IrDataValue::Boolean(_) => {}
            }
        }
        out.push('\n');
        Ok(())
    }

    fn emit_main(&self, out: &mut String) -> Result<(), LlvmCodegenError> {
        let entry = self
            .program
            .functions
            .iter()
            .find(|function| function.id == self.program.entry)
            .ok_or(LlvmCodegenError::MissingEntry {
                id: self.program.entry,
            })?;
        let entry_ret = llvm_type(&entry.return_type)?;
        out.push_str("define i32 @main() {\n");
        out.push_str("entry:\n");
        out.push_str(&format!(
            "  %entry_result = call {entry_ret} @{}()\n",
            llvm_function_name(entry)
        ));
        out.push_str("  ret i32 0\n");
        out.push_str("}\n");
        Ok(())
    }
}

struct FunctionEmitter<'a> {
    function: &'a IrFunction,
    signatures: &'a HashMap<String, FunctionSig>,
    data: &'a HashMap<DataId, &'a IrData>,
    local_types: HashMap<LocalId, IrTypeRef>,
    temp_types: HashMap<TempId, IrTypeRef>,
    param_types: HashMap<ParamId, IrTypeRef>,
    lines: Vec<String>,
    next_value_id: u32,
    block_terminated: bool,
}

impl<'a> FunctionEmitter<'a> {
    fn new(
        function: &'a IrFunction,
        signatures: &'a HashMap<String, FunctionSig>,
        data: &'a HashMap<DataId, &'a IrData>,
    ) -> Self {
        let local_types = function
            .locals
            .iter()
            .map(|local| (local.id, local.ty.clone()))
            .collect();
        let temp_types = function
            .temps
            .iter()
            .map(|temp| (temp.id, temp.ty.clone()))
            .collect();
        let param_types = function
            .params
            .iter()
            .map(|param| (param.id, param.ty.clone()))
            .collect();

        Self {
            function,
            signatures,
            data,
            local_types,
            temp_types,
            param_types,
            lines: Vec::new(),
            next_value_id: 0,
            block_terminated: false,
        }
    }

    fn emit(mut self, out: &mut String) -> Result<(), LlvmCodegenError> {
        let ret_ty = llvm_type(&self.function.return_type)?;
        let params = self
            .function
            .params
            .iter()
            .map(|param| Ok(format!("{} %p{}", llvm_type(&param.ty)?, param.id.0)))
            .collect::<Result<Vec<_>, LlvmCodegenError>>()?
            .join(", ");

        out.push_str(&format!(
            "define {ret_ty} @{}({params}) {{\n",
            llvm_function_name(self.function)
        ));
        out.push_str("entry:\n");

        for local in &self.function.locals {
            out.push_str(&format!(
                "  %l{}.addr = alloca {}\n",
                local.id.0,
                llvm_type(&local.ty)?
            ));
        }
        for temp in &self.function.temps {
            out.push_str(&format!(
                "  %t{}.addr = alloca {}\n",
                temp.id.0,
                llvm_type(&temp.ty)?
            ));
        }

        for instr in &self.function.body {
            self.emit_instr(instr)?;
        }

        if !self.block_terminated {
            self.lines.push("  unreachable".to_string());
        }

        for line in self.lines {
            out.push_str(&line);
            out.push('\n');
        }
        out.push_str("}\n");
        Ok(())
    }

    fn emit_instr(&mut self, instr: &IrInstr) -> Result<(), LlvmCodegenError> {
        match instr {
            IrInstr::Label(label) => {
                self.start_label(*label);
                Ok(())
            }
            IrInstr::Assign { dst, src } => {
                self.store_value(*dst, src)?;
                Ok(())
            }
            IrInstr::Unary { dst, op, value } => self.emit_unary(*dst, op, value),
            IrInstr::Binary {
                dst,
                op,
                left,
                right,
            } => self.emit_binary(*dst, op, left, right),
            IrInstr::Jump(label) => {
                self.lines.push(format!("  br label %L{}", label.0));
                self.block_terminated = true;
                Ok(())
            }
            IrInstr::Branch {
                cond,
                then_label,
                else_label,
            } => {
                let cond = self.read_value_as(cond, &IrTypeRef::Boolean)?;
                self.lines.push(format!(
                    "  br i1 {}, label %L{}, label %L{}",
                    cond.operand, then_label.0, else_label.0
                ));
                self.block_terminated = true;
                Ok(())
            }
            IrInstr::Call {
                dst,
                function,
                args,
            } => self.emit_call(*dst, function, args),
            IrInstr::Return(value) => self.emit_return(value.as_ref()),
            IrInstr::Allocate { .. } => Err(LlvmCodegenError::UnsupportedInstruction {
                instruction: "Allocate",
            }),
            IrInstr::GetAttr { .. } => Err(LlvmCodegenError::UnsupportedInstruction {
                instruction: "GetAttr",
            }),
            IrInstr::SetAttr { .. } => Err(LlvmCodegenError::UnsupportedInstruction {
                instruction: "SetAttr",
            }),
            IrInstr::VirtualCall { .. } => Err(LlvmCodegenError::UnsupportedInstruction {
                instruction: "VirtualCall",
            }),
            IrInstr::StaticCall { .. } => Err(LlvmCodegenError::UnsupportedInstruction {
                instruction: "StaticCall",
            }),
            IrInstr::BaseCall { .. } => Err(LlvmCodegenError::UnsupportedInstruction {
                instruction: "BaseCall",
            }),
            IrInstr::NewVector { .. } => Err(LlvmCodegenError::UnsupportedInstruction {
                instruction: "NewVector",
            }),
            IrInstr::VectorLen { .. } => Err(LlvmCodegenError::UnsupportedInstruction {
                instruction: "VectorLen",
            }),
            IrInstr::VectorPush { .. } => Err(LlvmCodegenError::UnsupportedInstruction {
                instruction: "VectorPush",
            }),
            IrInstr::VectorGet { .. } => Err(LlvmCodegenError::UnsupportedInstruction {
                instruction: "VectorGet",
            }),
            IrInstr::VectorSet { .. } => Err(LlvmCodegenError::UnsupportedInstruction {
                instruction: "VectorSet",
            }),
            IrInstr::MakeClosure { .. } => Err(LlvmCodegenError::UnsupportedInstruction {
                instruction: "MakeClosure",
            }),
            IrInstr::ClosureCall { .. } => Err(LlvmCodegenError::UnsupportedInstruction {
                instruction: "ClosureCall",
            }),
            IrInstr::TypeTest { .. } => Err(LlvmCodegenError::UnsupportedInstruction {
                instruction: "TypeTest",
            }),
            IrInstr::TypeCast { .. } => Err(LlvmCodegenError::UnsupportedInstruction {
                instruction: "TypeCast",
            }),
        }
    }

    fn start_label(&mut self, label: LabelId) {
        if !self.block_terminated {
            self.lines.push(format!("  br label %L{}", label.0));
        }
        self.lines.push(format!("L{}:", label.0));
        self.block_terminated = false;
    }

    fn emit_unary(
        &mut self,
        dst: IrPlace,
        op: &IrUnaryOp,
        value: &IrValue,
    ) -> Result<(), LlvmCodegenError> {
        let dst_ty = self.place_type(dst)?;
        match (op, &dst_ty) {
            (IrUnaryOp::Neg, IrTypeRef::Number) => {
                let value = self.read_value_as(value, &IrTypeRef::Number)?;
                let name = self.next_name("neg");
                self.lines
                    .push(format!("  {name} = fneg double {}", value.operand));
                self.store_operand(dst, &dst_ty, &name)
            }
            (IrUnaryOp::Not, IrTypeRef::Boolean) => {
                let value = self.read_value_as(value, &IrTypeRef::Boolean)?;
                let name = self.next_name("not");
                self.lines
                    .push(format!("  {name} = xor i1 {}, true", value.operand));
                self.store_operand(dst, &dst_ty, &name)
            }
            _ => Err(LlvmCodegenError::UnsupportedOperation {
                message: format!("unsupported unary operation {op:?} for {dst_ty}"),
            }),
        }
    }

    fn emit_binary(
        &mut self,
        dst: IrPlace,
        op: &IrBinaryOp,
        left: &IrValue,
        right: &IrValue,
    ) -> Result<(), LlvmCodegenError> {
        let dst_ty = self.place_type(dst)?;
        match op {
            IrBinaryOp::Add
            | IrBinaryOp::Sub
            | IrBinaryOp::Mul
            | IrBinaryOp::Div
            | IrBinaryOp::Mod
            | IrBinaryOp::Pow => self.emit_number_binary(dst, op, left, right, &dst_ty),
            IrBinaryOp::Lt | IrBinaryOp::Le | IrBinaryOp::Gt | IrBinaryOp::Ge => {
                self.emit_number_compare(dst, op, left, right, &dst_ty)
            }
            IrBinaryOp::Eq | IrBinaryOp::Neq => self.emit_equality(dst, op, left, right, &dst_ty),
            IrBinaryOp::And | IrBinaryOp::Or => {
                self.emit_bool_binary(dst, op, left, right, &dst_ty)
            }
            IrBinaryOp::Concat | IrBinaryOp::ConcatSpace => {
                Err(LlvmCodegenError::UnsupportedInstruction {
                    instruction: "StringConcat",
                })
            }
        }
    }

    fn emit_number_binary(
        &mut self,
        dst: IrPlace,
        op: &IrBinaryOp,
        left: &IrValue,
        right: &IrValue,
        dst_ty: &IrTypeRef,
    ) -> Result<(), LlvmCodegenError> {
        if *dst_ty != IrTypeRef::Number {
            return Err(LlvmCodegenError::TypeMismatch {
                expected: IrTypeRef::Number,
                found: dst_ty.clone(),
            });
        }
        let left = self.read_value_as(left, &IrTypeRef::Number)?;
        let right = self.read_value_as(right, &IrTypeRef::Number)?;
        let name = self.next_name("num");
        match op {
            IrBinaryOp::Add => self.lines.push(format!(
                "  {name} = fadd double {}, {}",
                left.operand, right.operand
            )),
            IrBinaryOp::Sub => self.lines.push(format!(
                "  {name} = fsub double {}, {}",
                left.operand, right.operand
            )),
            IrBinaryOp::Mul => self.lines.push(format!(
                "  {name} = fmul double {}, {}",
                left.operand, right.operand
            )),
            IrBinaryOp::Div => self.lines.push(format!(
                "  {name} = fdiv double {}, {}",
                left.operand, right.operand
            )),
            IrBinaryOp::Mod => self.lines.push(format!(
                "  {name} = frem double {}, {}",
                left.operand, right.operand
            )),
            IrBinaryOp::Pow => self.lines.push(format!(
                "  {name} = call double @hulk_pow(double {}, double {})",
                left.operand, right.operand
            )),
            _ => unreachable!("checked by caller"),
        }
        self.store_operand(dst, dst_ty, &name)
    }

    fn emit_number_compare(
        &mut self,
        dst: IrPlace,
        op: &IrBinaryOp,
        left: &IrValue,
        right: &IrValue,
        dst_ty: &IrTypeRef,
    ) -> Result<(), LlvmCodegenError> {
        if *dst_ty != IrTypeRef::Boolean {
            return Err(LlvmCodegenError::TypeMismatch {
                expected: IrTypeRef::Boolean,
                found: dst_ty.clone(),
            });
        }
        let left = self.read_value_as(left, &IrTypeRef::Number)?;
        let right = self.read_value_as(right, &IrTypeRef::Number)?;
        let pred = match op {
            IrBinaryOp::Lt => "olt",
            IrBinaryOp::Le => "ole",
            IrBinaryOp::Gt => "ogt",
            IrBinaryOp::Ge => "oge",
            _ => unreachable!("checked by caller"),
        };
        let name = self.next_name("cmp");
        self.lines.push(format!(
            "  {name} = fcmp {pred} double {}, {}",
            left.operand, right.operand
        ));
        self.store_operand(dst, dst_ty, &name)
    }

    fn emit_equality(
        &mut self,
        dst: IrPlace,
        op: &IrBinaryOp,
        left: &IrValue,
        right: &IrValue,
        dst_ty: &IrTypeRef,
    ) -> Result<(), LlvmCodegenError> {
        if *dst_ty != IrTypeRef::Boolean {
            return Err(LlvmCodegenError::TypeMismatch {
                expected: IrTypeRef::Boolean,
                found: dst_ty.clone(),
            });
        }
        let operand_ty = self.value_type(left)?;
        let pred = matches!(op, IrBinaryOp::Eq);
        let name = self.next_name("eq");
        match operand_ty {
            IrTypeRef::Number => {
                let left = self.read_value_as(left, &IrTypeRef::Number)?;
                let right = self.read_value_as(right, &IrTypeRef::Number)?;
                let op = if pred { "oeq" } else { "one" };
                self.lines.push(format!(
                    "  {name} = fcmp {op} double {}, {}",
                    left.operand, right.operand
                ));
            }
            IrTypeRef::Boolean => {
                let left = self.read_value_as(left, &IrTypeRef::Boolean)?;
                let right = self.read_value_as(right, &IrTypeRef::Boolean)?;
                let op = if pred { "eq" } else { "ne" };
                self.lines.push(format!(
                    "  {name} = icmp {op} i1 {}, {}",
                    left.operand, right.operand
                ));
            }
            other => {
                return Err(LlvmCodegenError::UnsupportedOperation {
                    message: format!("unsupported equality operand type {other}"),
                });
            }
        }
        self.store_operand(dst, dst_ty, &name)
    }

    fn emit_bool_binary(
        &mut self,
        dst: IrPlace,
        op: &IrBinaryOp,
        left: &IrValue,
        right: &IrValue,
        dst_ty: &IrTypeRef,
    ) -> Result<(), LlvmCodegenError> {
        if *dst_ty != IrTypeRef::Boolean {
            return Err(LlvmCodegenError::TypeMismatch {
                expected: IrTypeRef::Boolean,
                found: dst_ty.clone(),
            });
        }
        let left = self.read_value_as(left, &IrTypeRef::Boolean)?;
        let right = self.read_value_as(right, &IrTypeRef::Boolean)?;
        let name = self.next_name("bool");
        let instr = match op {
            IrBinaryOp::And => "and",
            IrBinaryOp::Or => "or",
            _ => unreachable!("checked by caller"),
        };
        self.lines.push(format!(
            "  {name} = {instr} i1 {}, {}",
            left.operand, right.operand
        ));
        self.store_operand(dst, dst_ty, &name)
    }

    fn emit_call(
        &mut self,
        dst: Option<IrPlace>,
        function: &str,
        args: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        match function {
            "print" => self.emit_print_call(dst, args),
            "sqrt" | "sin" | "cos" | "exp" | "log" | "rand" => {
                self.emit_math_builtin(dst, function, args)
            }
            name => self.emit_user_call(dst, name, args),
        }
    }

    fn emit_print_call(
        &mut self,
        dst: Option<IrPlace>,
        args: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        if args.len() != 1 {
            return Err(LlvmCodegenError::UnsupportedOperation {
                message: "print expects one argument".to_string(),
            });
        }
        let arg_ty = self.value_type(&args[0])?;
        match arg_ty {
            IrTypeRef::Number => {
                let arg = self.read_value_as(&args[0], &IrTypeRef::Number)?;
                self.lines.push(format!(
                    "  call void @hulk_print_number(double {})",
                    arg.operand
                ));
            }
            IrTypeRef::Boolean => {
                let arg = self.read_value_as(&args[0], &IrTypeRef::Boolean)?;
                let widened = self.next_name("bool8");
                self.lines
                    .push(format!("  {widened} = zext i1 {} to i8", arg.operand));
                self.lines
                    .push(format!("  call void @hulk_print_bool(i8 {widened})"));
            }
            IrTypeRef::String => {
                let arg = self.read_value_as(&args[0], &IrTypeRef::String)?;
                self.lines.push(format!(
                    "  call void @hulk_print_string(ptr {})",
                    arg.operand
                ));
            }
            other => {
                return Err(LlvmCodegenError::UnsupportedOperation {
                    message: format!("print for {other} is not implemented in the minimal backend"),
                });
            }
        }

        if let Some(dst) = dst {
            self.store_default(dst)?;
        }
        Ok(())
    }

    fn emit_math_builtin(
        &mut self,
        dst: Option<IrPlace>,
        function: &str,
        args: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        let runtime_name = match function {
            "sqrt" => "hulk_sqrt",
            "sin" => "hulk_sin",
            "cos" => "hulk_cos",
            "exp" => "hulk_exp",
            "log" => "hulk_log",
            "rand" => "hulk_rand",
            _ => unreachable!("checked by caller"),
        };
        let expected_arity = if function == "rand" {
            0
        } else if function == "log" {
            2
        } else {
            1
        };
        if args.len() != expected_arity {
            return Err(LlvmCodegenError::UnsupportedOperation {
                message: format!("{function} expects {expected_arity} arguments"),
            });
        }
        let mut rendered_args = Vec::new();
        for arg in args {
            let arg = self.read_value_as(arg, &IrTypeRef::Number)?;
            rendered_args.push(format!("double {}", arg.operand));
        }
        let result = self.next_name(function);
        self.lines.push(format!(
            "  {result} = call double @{runtime_name}({})",
            rendered_args.join(", ")
        ));
        if let Some(dst) = dst {
            self.store_operand(dst, &IrTypeRef::Number, &result)?;
        }
        Ok(())
    }

    fn emit_user_call(
        &mut self,
        dst: Option<IrPlace>,
        function: &str,
        args: &[IrValue],
    ) -> Result<(), LlvmCodegenError> {
        let sig = self.signatures.get(function).cloned().ok_or_else(|| {
            LlvmCodegenError::UnknownFunction {
                name: function.to_string(),
            }
        })?;
        if sig.params.len() != args.len() {
            return Err(LlvmCodegenError::UnsupportedOperation {
                message: format!(
                    "function '{function}' expects {} arguments, got {}",
                    sig.params.len(),
                    args.len()
                ),
            });
        }
        let mut rendered_args = Vec::new();
        for (arg, expected_ty) in args.iter().zip(&sig.params) {
            let arg = self.read_value_as(arg, expected_ty)?;
            rendered_args.push(format!("{} {}", llvm_type(expected_ty)?, arg.operand));
        }
        let ret_ty = llvm_type(&sig.ret)?;
        let call = format!(
            "call {ret_ty} @{}({})",
            sig.llvm_name,
            rendered_args.join(", ")
        );
        if let Some(dst) = dst {
            let result = self.next_name("call");
            self.lines.push(format!("  {result} = {call}"));
            self.store_operand(dst, &sig.ret, &result)?;
        } else {
            self.lines.push(format!("  {call}"));
        }
        Ok(())
    }

    fn emit_return(&mut self, value: Option<&IrValue>) -> Result<(), LlvmCodegenError> {
        if let Some(value) = value {
            let ret_ty = self.function.return_type.clone();
            let value = self.read_value_as(value, &ret_ty)?;
            self.lines
                .push(format!("  ret {} {}", llvm_type(&ret_ty)?, value.operand));
        } else {
            return Err(LlvmCodegenError::UnsupportedOperation {
                message: "return without value is not supported for non-void LLVM functions"
                    .to_string(),
            });
        }
        self.block_terminated = true;
        Ok(())
    }

    fn store_value(&mut self, dst: IrPlace, src: &IrValue) -> Result<(), LlvmCodegenError> {
        let dst_ty = self.place_type(dst)?;
        let src = self.read_value_as(src, &dst_ty)?;
        self.store_operand(dst, &dst_ty, &src.operand)
    }

    fn store_default(&mut self, dst: IrPlace) -> Result<(), LlvmCodegenError> {
        let dst_ty = self.place_type(dst)?;
        let default = default_value(&dst_ty)?;
        self.store_operand(dst, &dst_ty, &default)
    }

    fn store_operand(
        &mut self,
        dst: IrPlace,
        ty: &IrTypeRef,
        operand: &str,
    ) -> Result<(), LlvmCodegenError> {
        self.lines.push(format!(
            "  store {} {operand}, ptr {}",
            llvm_type(ty)?,
            self.place_ptr(dst)
        ));
        Ok(())
    }

    fn read_value_as(
        &mut self,
        value: &IrValue,
        expected_ty: &IrTypeRef,
    ) -> Result<TypedOperand, LlvmCodegenError> {
        match value {
            IrValue::Temp(id) => {
                let ty = self.temp_types.get(id).cloned().ok_or_else(|| {
                    LlvmCodegenError::UnknownValue {
                        name: format!("%t{}", id.0),
                    }
                })?;
                self.ensure_type(expected_ty, &ty)?;
                let name = self.next_name("load");
                self.lines.push(format!(
                    "  {name} = load {}, ptr %t{}.addr",
                    llvm_type(&ty)?,
                    id.0
                ));
                Ok(TypedOperand { operand: name, ty })
            }
            IrValue::Local(id) => {
                let ty = self.local_types.get(id).cloned().ok_or_else(|| {
                    LlvmCodegenError::UnknownValue {
                        name: format!("%l{}", id.0),
                    }
                })?;
                self.ensure_type(expected_ty, &ty)?;
                let name = self.next_name("load");
                self.lines.push(format!(
                    "  {name} = load {}, ptr %l{}.addr",
                    llvm_type(&ty)?,
                    id.0
                ));
                Ok(TypedOperand { operand: name, ty })
            }
            IrValue::Param(id) => {
                let ty = self.param_types.get(id).cloned().ok_or_else(|| {
                    LlvmCodegenError::UnknownValue {
                        name: format!("%p{}", id.0),
                    }
                })?;
                self.ensure_type(expected_ty, &ty)?;
                Ok(TypedOperand {
                    operand: format!("%p{}", id.0),
                    ty,
                })
            }
            IrValue::ConstNumber(value) => {
                self.ensure_type(expected_ty, &IrTypeRef::Number)?;
                Ok(TypedOperand {
                    operand: llvm_float(*value),
                    ty: IrTypeRef::Number,
                })
            }
            IrValue::ConstBool(value) => {
                self.ensure_type(expected_ty, &IrTypeRef::Boolean)?;
                Ok(TypedOperand {
                    operand: value.to_string(),
                    ty: IrTypeRef::Boolean,
                })
            }
            IrValue::Null | IrValue::Unit => Ok(TypedOperand {
                operand: default_value(expected_ty)?,
                ty: expected_ty.clone(),
            }),
            IrValue::DataRef(id) => self.read_data_ref(*id, expected_ty),
        }
    }

    fn value_type(&self, value: &IrValue) -> Result<IrTypeRef, LlvmCodegenError> {
        match value {
            IrValue::Temp(id) => {
                self.temp_types
                    .get(id)
                    .cloned()
                    .ok_or_else(|| LlvmCodegenError::UnknownValue {
                        name: format!("%t{}", id.0),
                    })
            }
            IrValue::Local(id) => {
                self.local_types
                    .get(id)
                    .cloned()
                    .ok_or_else(|| LlvmCodegenError::UnknownValue {
                        name: format!("%l{}", id.0),
                    })
            }
            IrValue::Param(id) => {
                self.param_types
                    .get(id)
                    .cloned()
                    .ok_or_else(|| LlvmCodegenError::UnknownValue {
                        name: format!("%p{}", id.0),
                    })
            }
            IrValue::ConstNumber(_) => Ok(IrTypeRef::Number),
            IrValue::ConstBool(_) => Ok(IrTypeRef::Boolean),
            IrValue::Null => Ok(IrTypeRef::Object),
            IrValue::Unit => Ok(IrTypeRef::Object),
            IrValue::DataRef(id) => self.data_type(*id),
        }
    }

    fn read_data_ref(
        &self,
        id: DataId,
        expected_ty: &IrTypeRef,
    ) -> Result<TypedOperand, LlvmCodegenError> {
        let data = self
            .data
            .get(&id)
            .ok_or(LlvmCodegenError::MissingData { id })?;
        match &data.value {
            IrDataValue::String(_) => {
                self.ensure_type(expected_ty, &IrTypeRef::String)?;
                Ok(TypedOperand {
                    operand: format!("@str_{}", id.0),
                    ty: IrTypeRef::String,
                })
            }
            IrDataValue::Number(_) | IrDataValue::Boolean(_) => {
                Err(LlvmCodegenError::UnsupportedInstruction {
                    instruction: "DataRef",
                })
            }
        }
    }

    fn data_type(&self, id: DataId) -> Result<IrTypeRef, LlvmCodegenError> {
        let data = self
            .data
            .get(&id)
            .ok_or(LlvmCodegenError::MissingData { id })?;
        match &data.value {
            IrDataValue::String(_) => Ok(IrTypeRef::String),
            IrDataValue::Number(_) | IrDataValue::Boolean(_) => {
                Err(LlvmCodegenError::UnsupportedInstruction {
                    instruction: "DataRef",
                })
            }
        }
    }

    fn place_type(&self, place: IrPlace) -> Result<IrTypeRef, LlvmCodegenError> {
        match place {
            IrPlace::Temp(id) => {
                self.temp_types
                    .get(&id)
                    .cloned()
                    .ok_or_else(|| LlvmCodegenError::UnknownValue {
                        name: format!("%t{}", id.0),
                    })
            }
            IrPlace::Local(id) => {
                self.local_types
                    .get(&id)
                    .cloned()
                    .ok_or_else(|| LlvmCodegenError::UnknownValue {
                        name: format!("%l{}", id.0),
                    })
            }
        }
    }

    fn place_ptr(&self, place: IrPlace) -> String {
        match place {
            IrPlace::Temp(id) => format!("%t{}.addr", id.0),
            IrPlace::Local(id) => format!("%l{}.addr", id.0),
        }
    }

    fn ensure_type(&self, expected: &IrTypeRef, found: &IrTypeRef) -> Result<(), LlvmCodegenError> {
        if expected == found {
            Ok(())
        } else {
            Err(LlvmCodegenError::TypeMismatch {
                expected: expected.clone(),
                found: found.clone(),
            })
        }
    }

    fn next_name(&mut self, prefix: &str) -> String {
        let id = self.next_value_id;
        self.next_value_id += 1;
        format!("%{prefix}.{id}")
    }
}

#[derive(Debug, Clone)]
struct TypedOperand {
    operand: String,
    #[allow(dead_code)]
    ty: IrTypeRef,
}

fn llvm_function_name(function: &IrFunction) -> String {
    if function.name == "entry" {
        "hulk_entry".to_string()
    } else {
        sanitize_symbol(&function.name)
    }
}

fn sanitize_symbol(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' || ch == '.' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn llvm_type(ty: &IrTypeRef) -> Result<&'static str, LlvmCodegenError> {
    match ty {
        IrTypeRef::Number => Ok("double"),
        IrTypeRef::Boolean => Ok("i1"),
        IrTypeRef::Object
        | IrTypeRef::User(_)
        | IrTypeRef::String
        | IrTypeRef::Vector(_)
        | IrTypeRef::Iterable(_)
        | IrTypeRef::Functor { .. } => Ok("ptr"),
        IrTypeRef::Unknown => Err(LlvmCodegenError::UnsupportedType { ty: ty.clone() }),
    }
}

fn default_value(ty: &IrTypeRef) -> Result<String, LlvmCodegenError> {
    match ty {
        IrTypeRef::Number => Ok("0.0".to_string()),
        IrTypeRef::Boolean => Ok("false".to_string()),
        IrTypeRef::Object
        | IrTypeRef::User(_)
        | IrTypeRef::String
        | IrTypeRef::Vector(_)
        | IrTypeRef::Iterable(_)
        | IrTypeRef::Functor { .. } => Ok("null".to_string()),
        IrTypeRef::Unknown => Err(LlvmCodegenError::UnsupportedType { ty: ty.clone() }),
    }
}

fn llvm_float(value: f64) -> String {
    if value.fract() == 0.0 {
        format!("{value:.1}")
    } else {
        value.to_string()
    }
}

fn llvm_string_bytes(bytes: &[u8]) -> String {
    let mut escaped = String::with_capacity(bytes.len() * 4 + 4);
    for byte in bytes {
        escaped.push_str(&format!("\\{:02X}", byte));
    }
    escaped.push_str("\\00");
    escaped
}

#[cfg(test)]
mod tests {
    use super::*;
    use hulk_ir::{
        DataId, FunctionId, IrBinaryOp, IrData, IrDataValue, IrFunction, IrFunctionKind, IrInstr,
        IrParam, IrPlace, IrProgram, IrTemp, IrTypeRef, IrValue, ParamId, TempId,
    };

    #[test]
    fn emits_minimal_print_program() {
        let program = IrProgram {
            types: vec![],
            data: vec![],
            functions: vec![IrFunction {
                id: FunctionId(0),
                name: "entry".to_string(),
                kind: IrFunctionKind::Entry,
                params: vec![],
                locals: vec![],
                temps: vec![
                    IrTemp {
                        id: TempId(0),
                        ty: IrTypeRef::Number,
                    },
                    IrTemp {
                        id: TempId(1),
                        ty: IrTypeRef::Object,
                    },
                ],
                return_type: IrTypeRef::Object,
                body: vec![
                    IrInstr::Binary {
                        dst: IrPlace::Temp(TempId(0)),
                        op: IrBinaryOp::Add,
                        left: IrValue::ConstNumber(2.0),
                        right: IrValue::ConstNumber(3.0),
                    },
                    IrInstr::Call {
                        dst: Some(IrPlace::Temp(TempId(1))),
                        function: "print".to_string(),
                        args: vec![IrValue::Temp(TempId(0))],
                    },
                    IrInstr::Return(Some(IrValue::Temp(TempId(1)))),
                ],
            }],
            entry: FunctionId(0),
        };

        let llvm = emit_llvm(&program).expect("codegen should pass");
        assert!(llvm.contains("declare void @hulk_print_number(double)"));
        assert!(llvm.contains("define ptr @hulk_entry()"));
        assert!(llvm.contains("fadd double 2.0, 3.0"));
        assert!(llvm.contains("call void @hulk_print_number(double"));
        assert!(llvm.contains("define i32 @main()"));
    }

    #[test]
    fn emits_user_function_call() {
        let program = IrProgram {
            types: vec![],
            data: vec![],
            functions: vec![
                IrFunction {
                    id: FunctionId(0),
                    name: "entry".to_string(),
                    kind: IrFunctionKind::Entry,
                    params: vec![],
                    locals: vec![],
                    temps: vec![IrTemp {
                        id: TempId(0),
                        ty: IrTypeRef::Number,
                    }],
                    return_type: IrTypeRef::Number,
                    body: vec![
                        IrInstr::Call {
                            dst: Some(IrPlace::Temp(TempId(0))),
                            function: "id".to_string(),
                            args: vec![IrValue::ConstNumber(4.0)],
                        },
                        IrInstr::Return(Some(IrValue::Temp(TempId(0)))),
                    ],
                },
                IrFunction {
                    id: FunctionId(1),
                    name: "id".to_string(),
                    kind: IrFunctionKind::Function,
                    params: vec![IrParam {
                        id: ParamId(0),
                        name: "x".to_string(),
                        ty: IrTypeRef::Number,
                    }],
                    locals: vec![],
                    temps: vec![],
                    return_type: IrTypeRef::Number,
                    body: vec![IrInstr::Return(Some(IrValue::Param(ParamId(0))))],
                },
            ],
            entry: FunctionId(0),
        };

        let llvm = emit_llvm(&program).expect("codegen should pass");
        assert!(llvm.contains("define double @id(double %p0)"));
        assert!(llvm.contains("call double @id(double 4.0)"));
    }

    #[test]
    fn emits_static_string_data_and_print_string() {
        let program = IrProgram {
            types: vec![],
            data: vec![IrData {
                id: DataId(0),
                value: IrDataValue::String("Hello".to_string()),
            }],
            functions: vec![IrFunction {
                id: FunctionId(0),
                name: "entry".to_string(),
                kind: IrFunctionKind::Entry,
                params: vec![],
                locals: vec![],
                temps: vec![IrTemp {
                    id: TempId(0),
                    ty: IrTypeRef::Object,
                }],
                return_type: IrTypeRef::Object,
                body: vec![
                    IrInstr::Call {
                        dst: Some(IrPlace::Temp(TempId(0))),
                        function: "print".to_string(),
                        args: vec![IrValue::DataRef(DataId(0))],
                    },
                    IrInstr::Return(Some(IrValue::Temp(TempId(0)))),
                ],
            }],
            entry: FunctionId(0),
        };

        let llvm = emit_llvm(&program).expect("codegen should pass");
        assert!(llvm.contains("%HulkString = type { i64, ptr }"));
        assert!(llvm.contains("@str_0_data = private unnamed_addr constant [6 x i8]"));
        assert!(llvm.contains("call void @hulk_print_string(ptr @str_0)"));
    }

    #[test]
    fn escapes_string_bytes_in_global_data() {
        let program = IrProgram {
            types: vec![],
            data: vec![IrData {
                id: DataId(0),
                value: IrDataValue::String("A\nB".to_string()),
            }],
            functions: vec![IrFunction {
                id: FunctionId(0),
                name: "entry".to_string(),
                kind: IrFunctionKind::Entry,
                params: vec![],
                locals: vec![],
                temps: vec![IrTemp {
                    id: TempId(0),
                    ty: IrTypeRef::Object,
                }],
                return_type: IrTypeRef::Object,
                body: vec![
                    IrInstr::Call {
                        dst: Some(IrPlace::Temp(TempId(0))),
                        function: "print".to_string(),
                        args: vec![IrValue::DataRef(DataId(0))],
                    },
                    IrInstr::Return(Some(IrValue::Temp(TempId(0)))),
                ],
            }],
            entry: FunctionId(0),
        };

        let llvm = emit_llvm(&program).expect("codegen should pass");
        assert!(llvm.contains("\\41\\0A\\42\\00"));
    }
}
